### ISSUE TITLE
*.rs is recognized as hercules files

### ISSUE THREAD

**Issue by zhou13** [rust-lang/rust.vim#10]
In vim's official `filetype.vim`, I found that in line 860:
````
au BufNewFile,BufRead *.vc,*.ev,*.rs,*.sum,*.errsum setf hercules
````

Maybe it is better to move `ftdetect` to `after/ftdetect`?

**Comment by chris-morgan** [comment]
The normal locations where our ftdetect stuff will go overrides the defaults. Do you have an actual situation where the original, hercules, file type detection is occurring?

**Comment by fmendez** [comment]
I'm currently having the same behaviour. Any rust file loaded are recognised as hercules files. If I reload my .vimrc from any of the rust file:  so $MYVIMRC the file type is correctly detected.

**Comment by acgtyrant** [comment]
@fmendez Try execute `set filetype=rust` in any rust file, then open the other rust files again, does it solve your problem?

**Comment by zhou13** [comment]
No.  That does not solve my problem.  It seems that on my gentoo box, `/usr/share/vim/vim74/filetype.vim` always has a higher priority than my vim's bundle.

**Comment by zhou13** [comment]
OK.  That's my fault. It is already stated in the document that

> Note: Vundle will not automatically detect Rust files properly if filetype on is executed before Vundle. Please check the quickstart for more details.

So I change my pathogen setting to
````
filetype off
call pathogen#runtime_append_all_bundles()
filetype plugin indent on
```

**Comment by matthauck** [comment]
hmm. I'm seeing this same problem using NeoBundle... I have `filetype plugin indent on` at the bottom of my vimrc, and i still get .rs files showing as "hercules"...

**Comment by jagtesh** [comment]
I'm experiencing the same problem as @matthauck, also with NeoBundle. Executing `set filetype=rust` seems to correct the problem temporarily. The workaround of adding `au BufRead,BufNewFile *.rs set filetype=rust` to the bottom of my `.vimrc` seems to make this more or less permanent. However, I'd like a proper solution to this. Any help is really appreciated!

**Comment by bcp1989** [comment]
I get this problem with Vundle. I also have the BufWrite BufRead autocmd hoods setup. @jagtesh workaround works for me.

**Comment by jagtesh** [comment]
@bcp1989  If it's good enough for everyone else, it's good enough for me.

**Comment by ankgupta** [comment]
I had the same problem with Vundle. In my case I had to move `syntax enable` after `call vundle#end()`

**Comment by bensinc** [comment]
@ankgupta's comment did the trick for me!

**Comment by nodakai** [comment]
Just to share some information: I don't use any plugin managers and directly source the `rust.vim` checkout under `~/.vim` by
```vim
set runtimepath+=$HOME/.vim/rust.vim
```

Automatic detection is working, too.

**Comment by ashwanidausodia** [comment]
If you use Vundle, put `filetype off` before `call vundle#begin()` and `filetype on` after `call vundle#end()`

**Comment by sdball** [comment]
In my case I thought I was smarter than the docs by telling plug to install `rust-lang/rust` instead of `rust-lang/rust.vim`. 😄 

Protip: `rust-lang/rust` is the language and `rust-lang/rust.vim` is the vim plugin. >_>
