### ISSUE TITLE
No syntax highlighting when installed via vim-plug

### ISSUE THREAD

**Issue by byteslayer7** [rust-lang/rust.vim#100]
I believe it also doesn't properly install the helptags. I don't know if this is an issue with that project or this one but I figured I'd start here. I tried multiple different vim package managers and both Vim and Neovim.

**Comment by SergioBenitez** [comment]
Works just fine for me. Are you using nightly? If so, see: https://github.com/rust-lang/rust.vim/issues/97 and https://github.com/rust-lang/rust.vim/pull/99.

**Comment by DarknessDolphin** [comment]
Had the same issue. Tried installing through Vundle. Solved the problem by using Pathogen. Hope it helps :)

**Comment by vicente-reyes** [comment]
For me it works with vim but not neovim
(installed with vim-plug too)

**Comment by da-x** [comment]
I am using vim-plug too. Please ping if the problem reproduces. Thanks!
