### ISSUE TITLE
Comment repeat broken in impl blocks.

### ISSUE THREAD

**Issue by sholsapp** [rust-lang/rust.vim#103]
Hi there,

I'm not sure if my terminology was correct, but I've noticed that comments aren't automatically repeated when hitting <enter> when inside an `impl` block.

E.g., the following works as I would expect:

```
///                          <hit enter here>
///                          <comment was repeated, cursor one space ahead>
pub struct Foo {}
```

But the following does not:

```
impl Foo {
    ///                        <hit enter here>
                                <comment was not repeated, cursor aligned with first />
    pub fn foo() {}
}
```

**Comment by chris-morgan** [comment]
Can’t reproduce with my configuration: Vim 7.4.2225, formatoptions=croqnlj. What is your configuration? (`:version` and `:set fo?`.)

**Comment by sholsapp** [comment]
I'm using Vim 7.3 on OS X and my options are formatoptions=croqnl. Is there something else I can share? Any tips on where to tweak, I can brute force/play around with things if I know where to look.

**Comment by chris-morgan** [comment]
Ah, Vim 7.3. I’m not surprised it works imperfectly there; there were a lot of bugs in some of these formatoptions back then. There’s nothing we can do about it. If you upgrade to ~7.4.1400 or later it’ll all work fine.

**Comment by sholsapp** [comment]
Switching to 7.4 does resolve the issue. Since 7.3 is the stock version that comes with El Capitan (OS X) nowadays it might make sense to make a note somewhere on the README.

Thanks!
