### ISSUE TITLE
None of the commands work when installed with Vundle.

### ISSUE THREAD

**Issue by pinkisemils** [rust-lang/rust.vim#108]
I installed and updated to the latest version today, and none of the `:Rust*` commands seem to be defined. `:help :RustFmt` works, and syntax is being highlighted, but nothing else works.

I'm running a nightly compiler, rust.vim from commit `fc11d02fee330df7b30c83a80f09dd0c60ab43ce` and Vim 8.0.

**Comment by ExpHP** [comment]
Just to provide a data point, I believe I am seeing the same thing? (however I use dein, not Vundle)

Like the OP, I find that `:help RustFmt` brings up help documentation, but `:RustFmt` or `:RustEmitIr` or etc. produces `E492: Not an editor command: RustEmitIr`.

To be clear, I've never tried these commands before, so I'm not sure what to expect; but neither the repo README nor the `:help` info suggest that there are any additional configuration steps required to enable these features.

I also tried wiping my plugins and reinstalling with commit b2a5429ccdf22d6fc8 (circa a year ago) and I still see the same results.

Various setup bits:
* Rust 1.12 installed through rustup v0.5.0
* VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Jun 16 2016 10:50:38) Included patches: 1-1689, all features except `-mouse_sysmouse -tag_any_white -footer -mzscheme -hangul_input -python -xfontset -ebcdic -xterm_save -sun_workshop -mouse_jsbterm`

**Comment by pinkisemils** [comment]
Coming back to the issue, everything works if I open any other filetype first, and then open a rust source file, in my case with ctrl+p. 

Even still, `RustEmitIr` and `RustEmitAsm` don't work, as they can't locate crates I've imported from outside. `RustFmt` works, but only if the code compiles. And it seems to slow down exponentially, as time goes on. That might be an issue with `rustfmt` itself.

**Comment by ExpHP** [comment]
Ah!  It is a good thing you mention filetypes, because I had completely forgotten this absolutely critical fact:

**I had at some point deliberately removed `filetype plugin on` from my vimrc.**

Sure enough, adding `filetype plugin on`, I find that `:RustFmt` becomes a usable command.

It sounds like for you, a plugin associated with that "other filetype" may be setting this option as well.

**Comment by pinkisemils** [comment]
Nope, everything else that would seemingly rely on `filetype plugin on` just works. And it does autodetect the file type if I open up a rust file _later on_. It's weird, but since it does work for you, it might be my particular config that's weird.

**Comment by Sjlver** [comment]
Do you have some other rust plugin? In my case, I had an old version of rust.vim lying around in `.vim/ftplugin/rust.vim`, and this conflicted with https://github.com/rust-lang/rust.vim/

**Comment by dorfsmay** [comment]
I had the exact same issue, and as @ExpHP said, adding `filetype plugin on` fixed it BUT only if it is after the plugin:

    Plugin 'rust-lang/rust.vim'
    call vundle#end()
    filetype plugin on

**Comment by concatime** [comment]
dorfsmay, I LOVE YOU!

**Comment by dorfsmay** [comment]
Hey @concatime, if this was useful, you should add a thumbs up on the Pull Request #150.

It took me a long time to find @ExpHP's comment here, which is how I solve this issue, I think it should be on the main README.md.

**Comment by concatime** [comment]
Done, and It has been a while since.

**Comment by da-x** [comment]
Reading the Vundle quickstart doc I am under the impression that it's more of a problem of configuring Vundle than using rust.vim. I extended the README.md nonetheless. Thanks!

**Comment by sylints** [comment]
On Vim 8, RustFmt was not working. As stated above, added "filetype plugin on" and it started working.

Also, I forgot that I had to add rustfmt to my toolchain (thought it was built-in). https://github.com/rust-lang-nursery/rustfmt
