### ISSUE TITLE
Errors in source cause file dump in command line if g:rustfmt_autosave is 1

### ISSUE THREAD

**Issue by oblitum** [rust-lang/rust.vim#109]
Simple steps to reproduce:
- `let g:rustfmt_autosave = 1`
- `:w` a rust file with contents:

``` rust
fn main() {
    let foo: Vec<_> = vec![1, 2, 3];
    x
    foo.push(4);
}
```

`x` will force an error that will make file contents to be dumped in the command line.

This relates with https://github.com/rust-lang/rust.vim/issues/75.

**Comment by euclio** [comment]
A workaround is to use `let g:rustfmt_fail_silently = 1`.

**Comment by bcallaars** [comment]
Thanks, that works for me. It was driving me crazy./

**Comment by euclio** [comment]
I mentioned this problem in #99. I think the solution would be to remove support for rustfmt error reporting. The same errors would be reported by rustc anyways, and it seems redundant to have to maintain two errorformats.

**Comment by oblitum** [comment]
@euclio many thanks.

**Comment by da-x** [comment]
Now in master, `g:rustfmt_autosave` should silence rustfmt error regardless of other options.
