### ISSUE TITLE
augroup should not be rust.vim

### ISSUE THREAD

**Issue by syml** [rust-lang/rust.vim#110]
augroup rust.vim conflicts with the automatic augroup created by ftdetect.

I have another rust plugin syml/rust-codefmt that has a ftdetect for *.rs files. Rust.vim causes a W19 warning when it deletes the rust.vim augroup on cleanup because the ftdetect autocommand is still used by my plugin.

**Comment by euclio** [comment]
Should be fixed by #124.

**Comment by da-x** [comment]
If the issue persists please reopen. Thanks!
