### ISSUE TITLE
Rust 1.12 new error format no longer works with `compiler/cargo.vim`

### ISSUE THREAD

**Issue by ideasman42** [rust-lang/rust.vim#112]
The newly added `-->` prefix to build errors isn't ignored in the quick-fix window.

eg:

```
  3 --> polys_simplify_collapse.rs|123| 11
  4 ||     |
  5 || 123 |     usize e_prev,
  6 ||     |           ^^^^^^     
```

In my case this attempts to load the file:

`/src/retrace/src/--> polys_simplify_collapse.rs` where it should load:

`/src/retrace/src/polys_simplify_collapse.rs`

**Comment by Ravenow** [comment]
Confirm here. I think something from with errorformat, but im not so good in vimscript to fix it :)

**Comment by dan-t** [comment]
I've also struggled with this, but the problem seems be, that the correct compiler
plugin has to be activated. If you activate it, then it works.

Try calling `:compiler cargo` and then `:make build`.

The easiest way to always activate the cargo compiler plugin for every
rust file put the call `compiler cargo` into `~/.vim/after/ftplugin/rust.vim`.

**Comment by Ravenow** [comment]
Dan-t, thats the point! Now it works like expected :

autocmd BufRead,BufNewFile Cargo.toml,Cargo.lock,*.rs compiler cargo
autocmd BufRead,BufNewFile Cargo.toml,Cargo.lock,*.rs noremap <buffer> <F9> :make build<CR>

**Comment by Ravenow** [comment]
as continue to my last message i found one more thing to test. if u set compiler to cargo, some errors catched fine, but some not, here is an example:

```
#[derive(Debug)]
struct Point {
    x: f32,
    y: f32,
}

fn main() {
    let p = Point { x: 0.0, y: 1.0 };
    println!("{?:}", p);
}

```

**Comment by emoon** [comment]
Is it possible to just have Rust.vim handle this? I don't call cargo directly (it's called indirectly) to compile my project so mapping `compiler cargo` to rs files causes issues for me.

**Comment by billiob** [comment]
#121 may fix the issue.
In my vim config, I have:
`autocmd FileType rust compiler cargo
autocmd FileType rust setl makeprg=cargo\ build`

**Comment by emoon** [comment]
Thanks!

**Comment by da-x** [comment]
This was fixed by other changes. Automatic `compiler cargo` is another open issue.
