### ISSUE TITLE
The option -Z is now unstable

### ISSUE THREAD

**Issue by mkollaro** [rust-lang/rust.vim#113]
I'm getting the following warning for all Rust files:
_The option `Z` is unstable and should only be used on the nightly compiler, but it is currently accepted for backwards compatibility; this will soon change, see issue [#31847](https://github.com/rust-lang/rust/issues/31847) for more details._

I'm using rustc 1.12.0 (3191fbae9 2016-09-23) and rust.vim ref 2030019.

```
Syntastic version: 3.6.0                                                                                                                 
Info for filetype: rust                                                                                                                  
Global mode: active                                                                                                                      
Filetype rust is active                                                                                                                  
The current file will be checked automatically                                                                                           
Available checker: rustc                                                                                                                 
Currently enabled checker: rustc
```

**Comment by steveklabnik** [comment]
Hm, https://github.com/rust-lang/rust.vim/blob/fc11d02fee330df7b30c83a80f09dd0c60ab43ce/autoload/rust.vim#L102 is the spot that it's used inside the extension. The file hasn't changed in a long time...

**Comment by spinda** [comment]
Is there any way to silence this warning for the time being? It's quite annoying having the Syntastic window always open for .rs files.

**Comment by Rolandde** [comment]
@spinda

     let g:syntastic_quiet_messages = {"regex": 'is unstable and should only be used on the nightly compiler, but it is currently accepted for backwards compatibility; this will soon change, see issue #31847 for more details'}

I'm not sure how this affects speed, but I doubt it will match any other errors.

**Comment by spinda** [comment]
Thank you!

**Comment by lpenz** [comment]
I've tried adding

    let g:syntastic_quiet_messages = {"regex": 'is unstable and should only be used on the nightly compiler, but it is currently accepted for backwards compatibility; this will soon change, see issue #31847 for more details'}

It does suppress the message, but I don't get any warnings from syntastic. I was only able to get syntastic working again by changing the plugin, initializing `makeprg` as follows:

    let makeprg = self.makeprgBuild({})

**Comment by BurntSushi** [comment]
I just had the chance to update my rust-vim package and I'm now experiencing this change. I'm not really sure how the existing configuration is supposed to work at all in most projects, since it's effectively just calling `rustc the_file.rs`. For example, such a command always fails on the first `extern crate` it sees, since `rustc` isn't told where to find the crate.

In order to make the syntastic plugin useful to me again, I added this to my `.vimrc`, which restores the original behavior:

```
let g:syntastic_rust_rustc_args = '-Zparse-only'
```

I mostly develop on nightly Rust, so I don't have any good answers for folks using stable Rust...

**Comment by lpenz** [comment]
The issue here is that -Zparse-only works only in nightly rust. So, adding it to the plugin will break stable.
Maybe add an option to the plugin that selects the rust channel? Or even detect it?

**Comment by BurntSushi** [comment]
> The issue here is that -Zparse-only works only in nightly rust.

Right. What I'm saying is that I don't understand how the current config works for anyone at any time. AFAIK, it will always fail if your code has any `extern crate` statements, no?

**Comment by lpenz** [comment]
I did a quick test here, and you are right.
I looked at what emacs' flycheck does, and it looks like it uses "-Z no-trans -Z unstable-options", which will also stop working, it seems. I'm not really sure where to go from here... Maybe the user can add -L for the paths of external crates?
