### ISSUE TITLE
Syntastic integration: rustc not enabled as a checker

### ISSUE THREAD

**Issue by jmatraszek** [rust-lang/rust.vim#118]
Using rustc stable (1.12.0), Vim 8.0, rust.vim 2030019e1a5d0593dc662a0c37f3d06c4de8c252 and Syntastic 3.7.0-243.
SyntasticInfo output:

```
Syntastic version: 3.7.0-243 (Vim 800, Linux, GUI)
Info for filetype: rust
Global mode: active
Filetype rust is active
The current file will be checked automatically
Available checker: rustc
Currently enabled checkers: -  
```

Nothing happens on save or calling SyntasticCheck.

After running `let g:syntastic_rust_checkers = ['rustc']` works as expected. Right now I am using `autocmd FileType rust let g:syntastic_rust_checkers = ['rustc']` in `.vimrc` as a workaround.

P.S. I know there is a bunch of other Syntastic related issues, but all of them seems to be different (problems with error format, rustc is enabled as a checker but still does not work etc. etc.).

**Comment by josephfrazier** [comment]
I experienced the same issue with rustc 1.12.1, Vim 8.0.55, rust.vim https://github.com/rust-lang/rust.vim/commit/59e5e2f8b7df21eb438124b95c7295da9c53e1d7, and Syntastic 3.8.0-3.
SyntasticInfo output:

```
Syntastic version: 3.8.0-3 (Vim 800, Darwin)
Info for filetype: rust
Global mode: active
Filetype rust is active
The current file will be checked automatically
Available checker: rustc
Currently enabled checkers: -
```

The workaround posted above worked for me (thanks @jmatraszek!)

**Comment by shiba89** [comment]
@jmatraszek is `autocmd FileType rust` really necessary? Shouldn't Syntastic itself manage filetypes?

**Comment by Gawen** [comment]
Thanks for the workaround.

I experience the same issue with rust.vim https://github.com/rust-lang/rust.vim/commit/eed97e75117faaf210cb6103cf39a797fe21bfbe, rustc 1.15.0 (nightly daf8c1dfc) and rustc 1.13.0, Vim 8.0, Syntastic 3.8.0-2.

```
Syntastic version: 3.8.0-2 (Vim 800, Linux, GUI)
Info for filetype: rust
Global mode: active
Filetype rust is active
The current file will be checked automatically
Available checker: rustc
Currently enabled checkers: -
```

**Comment by grawlinson** [comment]
Just chiming in to say that I had to do the same as others in this issue to solve this issue.

`let g:syntastic_rust_checkers = ['rustc']` inside my vimrc.

**Comment by ajcrites** [comment]
While this generally works, Syntastic will report errors for `extern crate ...`. Is there any way to suppress this?

**Comment by shiba89** [comment]
@ajcrites if you have cargo>=0.16 you can use it instead of rustc. Unfortunately cargo support is not yet merged in rust.vim but you can manually merge (aka copy-paste) it from one of this two pull request:

https://github.com/rust-lang/rust.vim/pull/147
https://github.com/rust-lang/rust.vim/pull/132

then check if it is detected with `:SyntasticInfo` and if everything is fine you can add `let g:syntastic_rust_checkers = ['rustc']` to your .vimrc. I'm using it and it seems to work fine.

**Comment by beamspease** [comment]
Would be great to see one of these pull requests get accepted. I found this from looking to see if cargo check was supported yet since I've been having to disable Syntastic now that my project has gotten large enough that it takes notable time to compile. Cargo check however is just a couple of seconds or so.

**Comment by kopp** [comment]
I realized that using `let g:syntastic_rust_checkers = ['rustc']` gave me bogus errors when I used external crates (see https://stackoverflow.com/q/32400231/2165903), using `cargo` works, as well as using `cargo rustc` -- where the latter is much faster (which I do not understand (yet?), but I'm new to rust and its ecosystem).

**Comment by tafia** [comment]
Same here for rust 1.22. Workaround is working fine. Would be good to put it on the readme at least.
Thanks anyway!

**Comment by seanmonstar** [comment]
Anyone driving by, #132 was merged. Just setting `let g:syntastic_rust_checkers = ['cargo']` in your vimrc will get you `cargo check` running on saves.

This could probably be closed.

**Comment by da-x** [comment]
`let g:syntastic_rust_checkers = ['cargo']` is now the default if nothing is specified. Thanks!
