### ISSUE TITLE
Highlight question_mark / ? operator

### ISSUE THREAD

**Issue by bluss** [rust-lang/rust.vim#122]
New feature in Rust 1.13: The ? operator.

I'm using this:

```vim
syn match rustQuestionMark "?"
hi rustQuestionMark cterm=bold ctermfg=124
```

The first line should be added, but what's a good default syntax for it? I'm not sure what to link it to.

**Comment by bluss** [comment]
That `syn match` is not enough to exclude it from matching `T: ?Sized` too, which shouldn't be highlighted the same way.

**Comment by seanmonstar** [comment]
For a default, such that it plays well with themes, it seems like it's belongs in the `Symbol` syntax group. This seems to work well for me.

```vim
syn match rustQuestionMark "?\([a-zA-Z]\+\)\@!"
hi def link rustQuestionMark Symbol
```

**Comment by seanmonstar** [comment]
I slipped, I meant `Special` not `Symbol`.
