### ISSUE TITLE
disable autoindent after a brace {

### ISSUE THREAD

**Issue by aalvarado** [rust-lang/rust.vim#125]
Is there a way to have the Rust plugin not auto indent after { (new line) ?

**Comment by michael-younkin** [comment]
There's no setting for this, but you can disable it pretty easily using your own vim settings (applied after the ftplugin) or by forking this repo and just deleting the indentation related stuff (which is pretty straightforward, there isn't much of it).

**Comment by aalvarado** [comment]
cool, I think I found how to do it :) sorry for the nonissue

**Comment by aalvarado** [comment]
for the curious:

```
au FileType rust setlocal nosmartindent
```
