### ISSUE TITLE
Add support for taking off trailing whitespace

### ISSUE THREAD

**Issue by GBGamer** [rust-lang/rust.vim#13]
It's a simple `autocmd FileType rs autocmd BufWritePre <buffer> :%s/\s\+$//e`

I don't know where this would go, or otherwise I would submit a PR.

**Comment by chris-morgan** [comment]
I do not believe that such behaviour is appropriate for rust.vim. It's not the sort of thing a file type plugin should do, to say nothing of the potential significance of trailing whitespace in Markdown in particular (two trailing spaces meaning a line break), which might be used in doc comments.

**Comment by GBGamer** [comment]
It's only used in rust files...
