### ISSUE TITLE
please submit to vim/vim

### ISSUE THREAD

**Issue by chrisbra** [rust-lang/rust.vim#134]
Hi,
could you please submit a snapshot/release version of syntax/rust.vim and possibly the filetype and indent script to vim/vim so we can distribute it with Vim? When you do, please mention who you are, the license under which this is developed and that you give us allowance to distribute it with Vim. It's okay to simply submit those files whenever you think you have a stable/release version of those files. Thanks.

vim/vim#1354

**Comment by steveklabnik** [comment]
I've always wanted to do this, but have been concerned about the quality; this has mostly been tossed together by tons of people over the years. Are you okay with doing review of these files when I submit, or are there some guidelines for best practices I should be reading?

**Comment by chrisbra** [comment]
If you have a working version that works reasonably well, it should be okay to include. I'll can review syntax, ftplugin and indent scripts to some extent so that would be okay (check for obvious errors, I don't use rust, so cannot check, that the syntax is okay). I believe, Bram always does some quick check, but I don't know what he is been doing exactly.

**Comment by steveklabnik** [comment]
Great! I'll submit it sometime later today then.

**Comment by steveklabnik** [comment]
patch sent https://github.com/vim/vim/pull/1356

**Comment by 8573** [comment]
Will having the plugin upstreamed make it more difficult to keep up-to-date (with, e.g., style team decisions)?

**Comment by steveklabnik** [comment]
> (with, e.g., style team decisions)?

That stuff is really happening in `rustfmt` directly, not so much here.

**Comment by chrisbra** [comment]
included as of vim/vim@3c2881dc11
