### ISSUE TITLE
rust.vim resets shiftwidth

### ISSUE THREAD

**Issue by equal-l2** [rust-lang/rust.vim#136]
I'm using vim with `shiftwidth=2`.
Whenever I open rust file, shiftwidth is reset to 4.

I'm sorry if it is intended or this plugin is not responsible of it.

**Comment by steveklabnik** [comment]
It's set by default by the plugin, yes. IIRC you can change it, I forget what the setting is. But four spaces is the standard Rust style.

**Comment by equal-l2** [comment]
Well, I will adjust myself to rust standard.

**Comment by andrewarrow** [comment]
this is hard for me. still looking for that setting.

**Comment by equal-l2** [comment]
`let g:rust_recommended_style = 0` will free you from the convention.
(I don't use this anymore, though)
