### ISSUE TITLE
`:RustFmt` closes all the open folds.

### ISSUE THREAD

**Issue by dpc** [rust-lang/rust.vim#138]
Similar issue have been reported for Go's `gofmt`: https://github.com/fatih/vim-go/issues/502

**Comment by siscia** [comment]
Confirm the issues, it is quite annoying...

**Comment by da-x** [comment]
Tested and fixed in master, please tell me how if it works for you.

Thanks!

**Comment by dpc** [comment]
@da-x Thank you so much! Works here.

**Comment by zacheryph** [comment]
I appear to be running into this issue? Running `:RustFmt` closes all folds.

```
VIM version 8.0.707

$ GIT_DIR=~/.vim/plugged/rust.vim/.git git rev-parse HEAD
ce8e0f7c467fe2612ef916ee0f4136bfa3d3ff57
```

**Comment by alok** [comment]
@zacheryph What's your config to get folding to work with fastfold? I'm having trouble with it and you're the only person on github who's mentioned both that I could find.

**Comment by zacheryph** [comment]
@alok I did not figure this out or spend the time to.  I just disabled fastfold [for the time being].
