### ISSUE TITLE
highlighting with space between function name and opening bracket '('

### ISSUE THREAD

**Issue by troubas** [rust-lang/rust.vim#139]
`string.clear()` gets highlighted, while `string.clear ()` does not.

Is this intentional? If not could you point me in the right direction to change it?

**Comment by steveklabnik** [comment]
I have no idea, but the space there is not standard Rust style, so it doesn't surprise me.

I would take a PR that highlights it anyway.

**Comment by troubas** [comment]
Hmm you're right. It's not rust standard style.

> Single-line calls
> 
> Do not put a space between the function name and open paren, between the open paren and the 
> first argument, or between the last argument and the close paren.

https://github.com/rust-lang-nursery/fmt-rfcs/blob/master/guide/guide.md

I think that we should not change this behavior after all. It pointed me to the style guide and might do the same for other people.
