### ISSUE TITLE
Bunch of errors when opening a rust file or editing it

### ISSUE THREAD

**Issue by Shir0kamii** [rust-lang/rust.vim#143]
Hello there!

I've just installed rust.vim and when I tried to open a `main.rs`, I've got the following errors:

```
Error detected while processing function <SNR>101_HandleExitNeoVim[1]..<SNR>101_HandleExit[27]..ale_linters#rust#rustc#HandleRustcErrors:
line   19:
E121: Undefined variable: code
Press ENTER or type command to continue
Error detected while processing function <SNR>101_HandleExitNeoVim[1]..<SNR>101_HandleExit[27]..ale_linters#rust#rustc#HandleRustcErrors:
line   19:
E116: Invalid arguments for function empty(l:error.code) && index(g:ale_rust_ignore_error_codes, l:error.code.code) > -1
Press ENTER or type command to continue
Error detected while processing function <SNR>101_HandleExitNeoVim[1]..<SNR>101_HandleExit[27]..ale_linters#rust#rustc#HandleRustcErrors:
line   19:
E15: Invalid expression: !empty(l:error.code) && index(g:ale_rust_ignore_error_codes, l:error.code.code) > -1
Press ENTER or type command to continue
```

I wondered if I did something wrong so I tried to clean the plugin and reinstall it but it didn't change.

Could anyone point me out what is the problem ? I'm not very familiar with the Vim scripting language.

I use neovim 0.1.7 if it can help.

**Comment by steveklabnik** [comment]
I wonder if this is a difference between neovim and vim, I don't know how neovim is different.

**Comment by SirDoctors** [comment]
I would vote that it isn't a neovim issue as I'm using neovim with this plugin without an issue.

**Comment by Shir0kamii** [comment]
What step can I take to debug this ? Sorry but I'm very novice when it comes to Vim's internals.

**Comment by steveklabnik** [comment]
I am too :fro
