### ISSUE TITLE
Suggestion: Option to highlight `unsafe` in bold

### ISSUE THREAD

**Issue by bluss** [rust-lang/rust.vim#144]
I'm not sure there is a good default highlighting that unsafe could be mapped to for this setting.

This is something I use in my Rust + Vim setup and I think that unsafe is not just another keyword, so it would be great to have this way of highlighting Rust spread.

**Comment by bluss** [comment]
If you want to add this tweak manually, you'd add into `after/syntax/rust.vim` (inside your vim configuration directory).
```vim
syn keyword rustUnsafeBold unsafe
hi rustUnsafeBold cterm=bold ctermfg=black
```

To incorporate this into rust.vim we'd need to make it conditional and preferably link it to a default syntax style instead.

**Comment by chris-morgan** [comment]
I have no intention of adding anything *custom* like this; we have no interest in the colour scheme business. The highlight groups in `:help group-name` are all we should link to.

Still, `Exception` might be a reasonable choice for `unsafe`.

**Comment by bluss** [comment]
I guess you mean there is no way to make it bold (often) by linking to predefined syntax groups?

**Comment by chris-morgan** [comment]
I mean that we cannot (or at least should not) control the highlighting of any syntax group. Linking to one of the standard ones while allowing the user to customise it if they choose is the most we should do.

**Comment by bluss** [comment]
Based on description in the docs, Todo seems like the most appropriate one.

```
	*Todo		anything that needs extra attention; mostly the
			keywords TODO FIXME and XXX
```

**Comment by chris-morgan** [comment]
I would definitely object to making the `unsafe` keyword `Todo`. As a rule I’d say `Todo` is expected to only be used inside comments—its highlighting is commonly “comment plus bold/italic” or “comment plus a background colour”.

`Exception` instead of `Keyword` is the furthest I’m willing to go.

**Comment by bluss** [comment]
I'm proposing something that the user can opt into, not a change to the default.

**Comment by chris-morgan** [comment]
Splitting `unsafe` out of `rustKeyword` to `rustUnsafeKeyword` or `rustUnsafe` is reasonable; but giving a knob to twiddle to link it to an unusual group doesn’t make sense. At that point the user has a special group that they can highlight or link as they desire—and I’d rather have you write `hi link rustUnsafeKeyword Todo` in your own config than something like `let g:rust_unsafe_keyword_as_todo = 1`.

**Comment by bluss** [comment]
That's a good idea, it reaches the goal of bold/flagged unsafe being a simple thing to opt into.
