### ISSUE TITLE
reintegrate changes from upstream

### ISSUE THREAD

**Issue by steveklabnik** [rust-lang/rust.vim#148]
https://github.com/vim/vim/commit/3c2881dc1195f53ebafc387378399ddd6cb677a7

**Comment by jacwah** [comment]
Hi @steveklabnik! I'd love to help. I'm unsure what should be done though. Should the linked commit be merged into rust.vim? I have no idea how collision between Vin "builtins" and plugins work. At a glance the patch seems to mostly copy what's in this repo.

**Comment by steveklabnik** [comment]
@jacwah hi! So, https://github.com/rust-lang/rust.vim/pull/152 actually fixed this! That's why you see the same thing 😄
