### ISSUE TITLE
Rust conceal not work

### ISSUE THREAD

**Issue by iho** [rust-lang/rust.vim#15]
```
let g:rust_conceal = 1 
let g:rust_conceal_mod_path = 1 
```

How to fix it? 

How to bind it?
!= to  ≢ or ≠
==  to ≡
<= to ≤

> = to ≥
> => to ⇒
> -> to →
> in to ∈
> / to ÷
> || to ∨
> && to ∧ 

How to deal with  "for x in iterator"?  ∀

**Comment by chris-morgan** [comment]
I had forgotten about the conceal stuff so I guess it shouldn’t be surprising if it broke somewhere along the way. My personal inclination is to remove it—I never really saw the point of it in the first place.

**Comment by pyjarrett** [comment]
I've been playing with conceal, but the highlighting ends up coming out with awful gray backgrounds without adding `hi clear conceal`.  I'm thinking of submitting a fix, but first I'm going to do some more research to see if this is a "feature" of my color schemes.

**Comment by chris-morgan** [comment]
@pyjarrett Yes, it’s a colourscheme feature.

**Comment by pyjarrett** [comment]
Submitted a fix for the color scheme issue in #70.
