### ISSUE TITLE
Extra forward slashes added when breaking multi-line string

### ISSUE THREAD

**Issue by jonhoo** [rust-lang/rust.vim#155]
This is a fun one. Consider the following code:
```rust
fn main() {
    println!("a//b//c//d");
}
```
Put the cursor right after `a`, and type `\` followed by a newline. Everything is fine:
```rust
fn main() {
    println!("a\
             //b//c//d");
}
```
Now put the cursor right after `b`, and do the same thing. Hmm:
```rust
fn main() {
    println!("a\
             //b\
             ////c//d");
}
```
I guess it decided to continue a comment or something? Let's try it again, `\` + newline after `c`:
```rust
fn main() {
    println!("a\
             //b\
             ////c\
             /////d");
}
```
Fun times were had by all.

**Comment by da-x** [comment]
This is done by Vim itself due to `setlocal formatoptions+=c`, from having `setlocal formatoptions-=t formatoptions+=croqnl` in `rust.vim`. Perhaps for this rare use case it's not worth the trouble to disable it, or to hook various insert conditions to detect that the cursor is inside a string and disabling it temporarily. What do you think?

**Comment by jonhoo** [comment]
I don' know what the benefits of `c` in `formatoptions` are? Is this generally something we want, and just something that bites us in this particular case?

**Comment by da-x** [comment]
Looked again at Vim docs, it's actually it's the `r` option:

```
r	Automatically insert the current comment leader after hitting
	<Enter> in Insert mode.
```

This feature's purpose, for when you are editing to extend a comment block prefixed with `//` (comment leader), you wouldn't need to type '//' each time you add a new line to it. Sounds like a useful feature, especially if you write a lot of comments.

**Comment by jonhoo** [comment]
I'm surprised that vim can't distinguish the case where the // is inside of a string :/ But I also can't seem to find any workarounds on the web. I guess this is just a limitation of vim's language understanding?

**Comment by da-x** [comment]
Theoretically Vim can already know that it's a string due to the highlighting, and I guess that if we implement a hook for `<Enter>` in insert mode we would use that.

I'll tag this as a known limitation with low priority of fixing. We got bigger fish to fry in rust.vim.
