### ISSUE TITLE
RustFmtRange doesn't work

### ISSUE THREAD

**Issue by jonhoo** [rust-lang/rust.vim#156]
Consider the following file:
```rust
fn foo() {
    let a
        =
        true;
}
```
Now run `:%RustFmtRange` -- notice how no changes are made (i.e., no formatting happens). The same happens if you highlight any subset of the lines and run `:RustFmtRange`.

**Comment by JekoTronik** [comment]
I got some trouble too. Don't know if mine is related...
Here is what :%RustFmtRange outputs (sorry, there is some french words) : 

> Erreur détectée en traitant function rustfmt#FormatRange..<SNR>30_RustfmtCommandRan
ge :
ligne    2 :
E117: Fonction inconnue : json_encode
E116: Arguments invalides pour la fonction printf("%s %s --write-mode=overwrite --f
ile-lines '[%s]'", g:rustfmt_command, g:rustfmt_options, json_encode(l:arg))
E15: Expression invalide : printf("%s %s --write-mode=overwrite --file-lines '[%s]'
", g:rustfmt_command, g:rustfmt_options, json_encode(l:arg))
  1 fn main(){    println!("Hello, Word!");
  2 }

**Comment by kgreenek** [comment]
Bump. I can also confirm that calling RustFmtRange doesn't work

**Comment by flip1995** [comment]
It seems this is a rustfmt issue. The `--file-lines` argument is not really finished yet. (See https://github.com/rust-lang-nursery/rustfmt/issues/1514) 

The reason it always does nothing is a different though. I will make a pull request regarding this.
