### ISSUE TITLE
Loop annotations are not highlighted correctly.

### ISSUE THREAD

**Issue by CleanCut** [rust-lang/rust.vim#159]
On current master, loop annotations are highlighted one way where they are defined, and a complete different way when they are used.

Here is on my MacVim 8.0.329 with theme colors chosen to be as close as possible to Monokai from Sublime Text.

![image](https://user-images.githubusercontent.com/5838512/27256260-ddae66dc-536c-11e7-95af-edec10645418.png)

Here's the same code in Atom with colors from the monokai community theme (you can tell what theme I like).

![image](https://user-images.githubusercontent.com/5838512/27256287-8899ae12-536d-11e7-9732-8dc6babcaa09.png)

**Comment by chris-morgan** [comment]
`'foo:` gets highlighted as `rustLabel` (including the colon).
`break 'foo` still uses `rustLifetime` for `'foo`. It could be adjusted to use `rustLabel`.

**Comment by CleanCut** [comment]
It appears `continue` is also being highlighted as `rustLifetime`.  It should definitely be `rustLabel` for both `break 'label` and `continue 'label`, since they are labels.

Interesting that GitHub highlights the apostrophe, label, and colon each separately.  I don't have an opinion on that, I just want the labels to be the same in both places.

```rust
'label: loop {
    break 'label;
    continue 'label;
}
```
