### ISSUE TITLE
Delete to match (%) no longer works for angle brackets

### ISSUE THREAD

**Issue by jonhoo** [rust-lang/rust.vim#160]
The [`%`  command](http://vimdoc.sourceforge.net/htmldoc/motion.html#%25) is supposed to jump to the match of the item under the cursor (e.g., to the matching `)` for a `(`). This used to work for `<` and `>`, but seems to have broken some time recently. Consider the file:
```rust
fn foo<T>(_: T) {}
```
Place the cursor on `<` and press `d%`. This *should* delete just `<T>`, but instead deletes all of `<T>(_: T)` (`%` will delete to the first opening bracket, and then to its match). This suggests that `<` and `>` are no longer identified as matches. This is controlled by the [`matchpairs` option](http://vimdoc.sourceforge.net/htmldoc/options.html#'matchpairs'). rust.vim should probably include something like `:set mps+=<:>`.

**Comment by chris-morgan** [comment]
This was apparently removed in [merging upstream changes back into this repository](https://github.com/rust-lang/rust.vim/commit/b5d4cc25122586939df0a5c68391f649f6c83bd8#diff-9f6aaa9ba985bf46731062ecf337d32aL194). I have no idea why it would have been removed. We should investigate this further.

**Comment by chris-morgan** [comment]
I have reinstated this in the form conventional among Vim syntax files: *support* matchit.vim, but don’t *load* it.

If you are using Vim 8, add this to your vimrc:

```vim
 packadd! matchit
```

Otherwise, I think this should do it:

```vim
runtime macros/matchit.vim
```
