### ISSUE TITLE
Vundle script broken

### ISSUE THREAD

**Issue by syncharny** [rust-lang/rust.vim#162]
When trying to install via vundle I get this error:

> vim +PluginInstall +qall
Error detected while processing /Users/../.vim/bundle/rust.vim/plugin/rust.vim:
line    4:
E492: Not an editor command: ^M
line    5:
E15: Invalid expression: exists("g:loaded_syntastic_rust_filetype")^M
line   22:
E488: Trailing characters
line   23:
E171: Missing :endif
Press ENTER or type command to continue

**Comment by syncharny** [comment]
dos2unix will fix it, but those trailing characters shouldnt be there

**Comment by da-x** [comment]
We don't seem to have LF characters in those files. It's probably an unrelated issue. If issue persists please reopen. Thanks!
