### ISSUE TITLE
Broken with rustfmt-nightly

### ISSUE THREAD

**Issue by kybishop** [rust-lang/rust.vim#164]
After upgrading to rustfmt nightly via `cargo install rustfmt-nightly`, rustfmt no longer works via rust.vim, even though `rustfmt` from the command line works fine.

Sanity checking my settings:

```bash
➜ cat ~/.vimrc|ag rustfmt
let g:rustfmt_command = '/Users/kybishop/.cargo/bin/rustfmt'
let g:rustfmt_autosave = 1 " format Rust files on save
let g:rustfmt_fail_silently = 1 " else rustfmt will bring cursor to bottom of window on syntax failure
➜ which rustfmt
/Users/kybishop/.cargo/bin/rustfmt
➜ rustfmt -V
0.1.8-nightly ( )
```

When attempting to run `:RustFmt` manually, I get a message that states "Command terminated", with no alteration to the file.

**Comment by zaynetro** [comment]
You can specify command that will be used to format the file. Rustfmt suggests using `cargo fmt` to do so.

Add the following to your vimrc file:

```
let g:rustfmt_command = "cargo fmt -- "
```

**Comment by kybishop** [comment]
That did the trick! Thanks @zaynetro

**Comment by rigelrozanski** [comment]
Similar issues, I would suggest re-opening this issue until adequate documentation is added to specify that the old rustfmt must be used - right now the documentation train leads one to install rustfmt-nightly without any warnings of incompatibility
