### ISSUE TITLE
Support color cargo/rustc output

### ISSUE THREAD

**Issue by mqudsi** [rust-lang/rust.vim#165]
Is it possible to get colorize output from `:make` when `compiler` is `rustc` or `cargo`?

**Comment by landersson** [comment]
I'd also really like to get coloured rustc output when running RustRun... any way to make that happen?

**Comment by da-x** [comment]
Vim does not support retaining terminal coloring information from `makeprg` executions into the quickfix list. For the RustRun alternative you can invoke it directly via `:!rustc %f`, or do a `cargo build` via `Cbuild`, though then you don't get errors into quickfix list. Anyway, it's too much of a Vim limitation to work around — sorry. There are some plugins these days for asynchronous error checking that you may find useful, though, to complement rust.vim.
