### ISSUE TITLE
Have yield not be highlighted as a reserved word

### ISSUE THREAD

**Issue by mgattozzi** [rust-lang/rust.vim#170]
Right now Generators have landed in Rust nightly due to an eRFC. `yield` is one of the keywords used in it. While this works it's annoying to have the syntax highlighted as unusable since it's a reserved word. Would it be possible to make it colored like other keywords in Rust? One downside would be that the syntax would be seen as valid on stable.

**Comment by steveklabnik** [comment]
merged https://github.com/rust-lang/rust.vim/pull/172 !
