### ISSUE TITLE
Syntastic reports `main function not found` on library crate

### ISSUE THREAD

**Issue by MasonRemaley** [rust-lang/rust.vim#180]
Not sure why this is happening, it seems someone else saw this in #173 but the issue was closed for some reason.

**Comment by cadubentzen** [comment]
This is happening here too.

**Comment by da-x** [comment]
This is another result of specifying `let g:syntastic_rust_checkers = [`rustc`]` and trying to edit an '.rs' file that is not a standalone program. I changed the default to be the `cargo` checker, so users should not bump on this anymore.
