### ISSUE TITLE
Incorrect where clauses indentation

### ISSUE THREAD

**Issue by stjepang** [rust-lang/rust.vim#189]
I have the following code:

```rust
pub fn get<Q>(&self, key: &Q) -> Option<Entry<K, V>>
where
    K: Borrow<Q>,
    Q: Ord + ?Sized,
{
    self.inner.get(key).map(Entry::new)
}
```

Selecting all lines and reindenting with `=` results in:

```rust
pub fn get<Q>(&self, key: &Q) -> Option<Entry<K, V>>
    where
    K: Borrow<Q>,
    Q: Ord + ?Sized,
    {
        self.inner.get(key).map(Entry::new)
    }
```

**Comment by terrybrashaw** [comment]
Just ran into this. Here's the [`where` clause style guidelines](https://github.com/rust-lang-nursery/fmt-rfcs/blob/d8ebefbd4f9dda352e17f41843e0add63fa5b90e/guide/items.md#where-clauses), for expected behavior.

**Comment by da-x** [comment]
Fixed in master. Please test!

**Comment by pickfire** [comment]
Even though this works but it does not auto reindent on the fly. I added this ability in kakoune https://github.com/mawww/kakoune/blob/master/test/indent/rust/before-where/in, it correctly indents on the fly even though there are no re-indent ability. Not quite sure how to do this in vim, I haven't used vim for quite some time after switching to kakoune but I hope vim gets this too.
