### ISSUE TITLE
Error on Write

### ISSUE THREAD

**Issue by vincecarney** [rust-lang/rust.vim#19]
I've installed the vim plugin with Pathogen and get the following error on initial write:

```
"main.rs" 4L, 77C written
Error detected while processing function 245..191:
line    9:
E700: Unknown function: SyntaxCheckers_rust_rustc_IsAvailable
Error detected while processing function <SNR>43_UpdateErrors..<SNR>43_CacheErrors..248..250..256..196:
line    1:
E15: Invalid expression: self._isAvailableFunc()
E15: Invalid expression: self._isAvailableFunc()
```

Subsequent writes to the same file produce:

```
"main.rs" 4L, 77C written
Error detected while processing function <SNR>43_UpdateErrors..<SNR>43_CacheErrors..248..250..256..196:
line    1:
E15: Invalid expression: self._isAvailableFunc()
E15: Invalid expression: self._isAvailableFunc()
```

**Comment by chris-morgan** [comment]
Sorry I missed this—I was away at the time and a couple of emails slipped through unnoticed until today.

I have never observed anything like this; is your copy of syntastic up to date?

**Comment by killpack** [comment]
I ran into the same problem, and updating my version of Syntastic appeared to fix it.

**Comment by ZhangZhuoSJTU** [comment]
Same problem, and no idea about it

**Comment by da-x** [comment]
Please reopen if reproducible with latest versions. Thanks!
