### ISSUE TITLE
syntastic broken 1.24

### ISSUE THREAD

**Issue by scirner22** [rust-lang/rust.vim#196]
I recently upgraded to rust 1.24 and syntastic has been broken for me ever since. I use syntastic with the following config `let g:syntastic_rust_checkers = ['cargo']`.

```
NVIM v0.2.2
rustc 1.24.0
cargo 0.25.0
```

**Comment by dmillard** [comment]
syntastic is also broken for me with the `cargo` checker. I'm a new user of rust.vim and thus don't have a point of comparison to old versions. The `rustc` checker does work, but gives extraneous errors on `extern crate ...` lines.

Interestingly for me, calling `:Errors` with the `cargo` checker shows up with the correct error list, implying syntastic has a good idea of what the errors _should_ be.

```rust
fn main() {
    garbage;
}
```

`:SyntasticInfo`
```
Syntastic version: 3.8.0-108 (Vim 800, Linux, GUI)
Info for filetype: rust
Global mode: active
Filetype rust is active
The current file will be checked automatically
Available checkers: cargo rustc
Currently enabled checker: cargo
```

`:let g:syntastic_debug=3 | SyntasticCheck`
```
syntastic: 13.622056: g:syntastic_version = '3.8.0-108 (Vim 800, Linux, GUI)'
syntastic: 13.622201: &shell = '/usr/bin/zsh', &shellcmdflag = '-c', &shellpipe = '2>&1| tee', &shellquote = '', &shellredir = '>%s 2>&1', &shelltemp = 1, &shellxquote = '', &autochdir = 0, &shellxescape = ''
syntastic: 13.622696: UpdateErrors: default checkers
syntastic: 13.622925: CacheErrors: default checkers
syntastic: 13.623481: g:syntastic_aggregate_errors = 0
syntastic: 13.623660: getcwd() = '<path>'
syntastic: 13.650012: system: command run in 0.024905s
syntastic: 13.650403: CacheErrors: Invoking checker: rust/cargo
syntastic: 13.651053: SyntasticMake: called with options: {'cwd': '<path>/src', 'errorformat': '%-G,%-Gerror: aborting %.%#,%-Gerror: Could not compile %.%#,%Eerror:%m,%Eerror[E%n]: %m,%Wwarning: %m,%Inote: %m,%C %#--> %f:%l:%c', 'makeprg': 'cargo check'}
syntastic: 13.953781: system: command run in 0.302281s
syntastic: 13.954117: checker output: ['   Compiling guessing_game v0.1.0 (file:///<path>)', 'error[E0425]: cannot find value `garbage` in this scope', ' --> src/main.rs:2:5', '  |', '2 |     garbage;', '  |     ^^^^^^^ not found in this scope', '', 'error: aborting due to previous error', '', 'error: Could not compile `guessing_game`.', '', 'To learn more, run the command again with --verbose.', '']
syntastic: 13.955414: raw loclist: [{'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type': '', 'pattern': '', 'text': '   Compiling guessing_game v0.1.0 (file:///<path>)'}, {'lnum': 2, 'bufnr': 2, 'col': 5, 'valid': 1, 'vcol': 0, 'nr': 425, 'type': 'E', 'pattern': '', 'text': 'cannot find value `garbage` in this scope'}, {'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type': '', 'pattern': '', 'text': '  |'}, {'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type': '', 'pattern': '', 'text': '2 |     garbage;'}, {'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type': '', 'pattern': '', 'text': '  |     ^^^^^^^ not found in this scope'}, {'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type': '', 'pattern': '', 'text': 'To learn more, run the command again with --verbose.'}]
syntastic: 13.956146: getLocList: checker rust/cargo returned 101
syntastic: 13.956419: rust/cargo raw: [{'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type': '', 'pattern': '', 'text': '   Compiling guessing_game v0.1.0 (file:///<path>)'}, {'lnum': 2, 'bufnr': 2, 'col': 5, 'valid': 1, 'vcol': 0, 'nr': 425, 'type': 'E', 'pattern': '', 'text': 'cannot find value `garbage` in this scope'}, {'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type': '', 'pattern': '', 'text': '  |'}, {'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type': '', 'pattern': '', 'text': '2 |     garbage;'}, {'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type': '', 'pattern': '', 'text': '  |     ^^^^^^^ not found in this scope'}, {'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type': '', 'pattern': '', 'text': 'To learn more, run the command again with --verbose.'}]
syntastic: 13.957123: quiet_messages filter: {}
syntastic: 13.957384: getLocList: checker rust/cargo run in 0.306820s
syntastic: 13.958171: aggregated: {'_sorted': 0, '_name': 'cargo (rust)', '_owner': 1, '_columns': 1, '_rawLoclist': [{'lnum': 2, 'bufnr': 2, 'col': 5, 'valid': 1, 'vcol': 0, 'nr': 425, 'type': 'E', 'pattern': '', 'text': 'cannot find value `garbage` in this scope'}]}
```

So it seems clear that syntastic is aware of the errors but is not displaying them. I'm unable to determine why `rustc` works.

**Comment by scirner22** [comment]
I believe the bug is in displaying error/warning results in the gutter. Syntastic is reporting the error count in `vim-airline` correctly.

**Comment by mlmeola** [comment]
It's not only the gutter. I do see errors in the location list, but if I press enter on them it replaces the .rs buffer with an empty buffer instead of going to the error in the .rs buffer.

**Comment by moses-palmer** [comment]
This issue started happening for me as well when upgrading ro _Rust 1.24_.

The location list is populated correctly, but signs are not shown. Furthermore, executing `:lprev` or `:lnext` completely freezes _vim_, requiring rapidly pressing _ctrl+c_ to even be able to execute `:x`; the _vim_ process will consume 100% of one core until terminated.

**Comment by alxdb** [comment]
I am also experiencing this error with rust 1.24, Vim 8.0 and cargo 0.25. However, using `:lprev` or `:lnext` doesn't freeze vim, it just tells me there are no more items.

Errors do show up in vim-airline and when using `:Errors` though. Also when opening the error from the location list I am taken to the error correctly, and the error then shows up in the Gutter.

I can't seem to get the output of `:let g:syntastic_debug=3 | SyntasticCheck` to stick around long enough for me to look at the output.

**Comment by popravich** [comment]
I've managed to make it work, please check linked PR

**Comment by da-x** [comment]
I've done a related fix in master - Syntastic should work regardless of the current directory. Would you please test and tell if it works for you? 

Thanks!

**Comment by ForsakenHarmony** [comment]
I'm having the same problem as @moses-palmer I think

when I open a rust file vim freezes (doesn't even display the file) and runs cargo check (?)

I can press ctrl-c to stop it and it works normally after that I think, but when I open another buffer/switch between buffers it happens again

**Comment by manonthemat** [comment]
This seems to be happening again.
After hitting ctrl-c, it _works_ until the next save.
