### ISSUE TITLE
Signs not showing on write (syntastic)

### ISSUE THREAD

**Issue by tuzz** [rust-lang/rust.vim#197]
I posted an issue for [Syntastic](https://github.com/vim-syntastic/syntastic/issues/2156), but maybe the problem is with rust.vim.

In short, the gutter signs aren't showing when I write a buffer, even though Syntastic is running. The location list is being populated and the signs only show after selecting an item.

I had a look through the source code but couldn't figure it out.

**Comment by mikeswoods** [comment]
I'm having the same problem. Errors appear in the location list, but no signs show up for the same errors, at least when using `cargo`. This functionality was working as of rustc 1.23. After I updated to 1.24, rust.vim stopped working as it did before.
