### ISSUE TITLE
Why there is no highlight for `match`?

### ISSUE THREAD

**Issue by Azure-Vani** [rust-lang/rust.vim#20]
I believed that `match` is a keyword like `let` and `fn` in rust, but only to found there is no highlight for `match`.

Is it a bug or feature?

**Comment by chris-morgan** [comment]
`match` is a keyword in this syntax file and has always been. If you’re not observing it, check if you’re actually using the appropriate file type and that it is loading these files and not another `syntax/rust.vim` from earlier in the runtimepath.

**Comment by igorgue** [comment]
I'm getting this problem right now, any ideas on how to debug this? Only `match` and `pub` aren't getting color highlighted
