### ISSUE TITLE
rustc not automatically registered with syntastic

### ISSUE THREAD

**Issue by klnusbaum** [rust-lang/rust.vim#200]
I recently installed `rust.vim` via `vim-plug`. When I did, I was disappointed to find that I was not getting any syntax checking. It wasn't until I added the following to my `init.vim` that I was able to get syntax checking on buffer write:

`let g:syntastic_rust_checkers = ['rustc']`

**Comment by klnusbaum** [comment]
I have a feeling you might actually always need to do this (i.e. it's not advisable to add something like the above line automatically without the user knowing). If that's the case, we should update the README to indicate this. Happy to make a small PR if that's the best course of action.

**Comment by da-x** [comment]
A pull request is most welcomed! Thanks
