### ISSUE TITLE
cargo checker is not jumping to the first error

### ISSUE THREAD

**Issue by temaput** [rust-lang/rust.vim#202]
Hi! My issue is with commit 29c61e1
Adding cwd somehow prevents my vim from opening errors list and actually acknowledging any errors in main.rs
If i remove cwd from SyntasticMake in cargo.vim, normal functionality is restored.

My vim is 
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Apr  4 2018 11:34:33)
macOS version
Included patches: 1-1633
Compiled by Homebrew

**Comment by da-x** [comment]
This may be fixed now, see #214

**Comment by da-x** [comment]
Please reopen if relevant. Thanks!
