### ISSUE TITLE
rustfmt doesn't keep file permissions

### ISSUE THREAD

**Issue by sguillia** [rust-lang/rust.vim#207]
Hello,

I would like Vim to simply keep my file permissions when editing.

```
$ touch test.rs
$ chmod +x test.rs
$ ls -l test.rs  
-rwxrwxr-x 1 user user 0 Apr 24 00:41 test.rs
$ vim test.rs +wq
$ ls -l test.rs  
-rw-rw-r-- 1 user user 1 Apr 24 00:42 test.rs
```

My file loses its executable bit. When running without vimrc files, it works normally.

```
$ chmod +x test.rs
$ vim -u NONE test.rs +wq
$ ls -l test.rs  
-rwxrwxr-x 1 user user 0 Apr 24 00:41 test.rs
```

The bug lives in this file:
https://github.com/rust-lang/rust.vim/blob/master/autoload/rustfmt.vim

A temporary file is created with default permissions, and is then renamed into `test.rs`.

Those two lines do fix the problem:
```
let permissions = system("stat -c '%a' '" . expand('%') . "' | tr -d '\n'")
let _ = system("chmod " . permissions . " '" . l:tmpname . "'")
```
Put them right before the _rename_ and it will work. The first line returns the file permissions like "755" without newline, the second one does apply those permissions.

Those are my first lines of vim script. I'm pretty sure I forgot something like shell-escaping filenames or other portability concerns.

Could you please review and merge those two lines or come up with another solution that keeps file permissions by design?

Thank you!

**Comment by joaodelgado** [comment]
Related: #188

**Comment by da-x** [comment]
You can try it out now.
