### ISSUE TITLE
Syntastic 'cargo' cwd problems

### ISSUE THREAD

**Issue by MarkSwanson** [rust-lang/rust.vim#210]
Syntastic is showing me a location list full of errors.
Unfortunately the pathnames for all of the errors are wrong. Cargo is presenting pathnames relative to the Cargo.lock file, but I've started vim like this:
$ cd cargo_member/src/bin
$ vi file.rs

So the location list contains:
cargo_member/src/bin/file.rs

But my CWD in vim is already cargo_member/src/bin

So when I ":lnext" syntastic/vim fails to find the file because it's looking for: cargo_member/src/bin/cargo_member/src/bin/file.rs

Solution?: 'fix' the file paths that Cargo returns to be relative to Vim's CWD.
  We know Cargo will include everything up to the dir containing Cargo.lock. Maybe it would be easy to remove the set of dirs in the pathname based on the CWD. 
  example: change %f in the errorformat from cargo_member/src/bin/file.rs to be just file.rs (if the CWD contains cargo_member/src/bin/)

**Comment by doomrobo** [comment]
Hey, would you be able to check if #218 fixes your issue? Thanks!

**Comment by da-x** [comment]
I've done a related fix in master - Syntastic should work regardless of the current directory. Would you please test and tell if it works for you? Thanks!
