### ISSUE TITLE
Put rust book in vim ':help' command

### ISSUE THREAD

**Issue by JotaPe** [rust-lang/rust.vim#211]
I think we need to have the Rust book on the doc folder for people that want to start with the language and want to have the book in offline mode don't need to use other ways to get the offline version, and if you see VSCode and Intellij plugins for Rust have the docs for the lang.

**Comment by da-x** [comment]
There's a really good additional plugin - [rust-doc](https://github.com/rhysd/rust-doc.vim), currently providing this functionality to some degree.
