### ISSUE TITLE
:RustFmt not work with rustfmt 0.7.0

### ISSUE THREAD

**Issue by Matrix-Zhang** [rust-lang/rust.vim#212]
as the topic

**Comment by phansch** [comment]
This is probably because of https://github.com/rust-lang-nursery/rustfmt/commit/5d9f5aa05a668e7dfef87b46d89dad2884df9d41, which replaces `--write-mode` with `--emit`.

**Comment by Marwes** [comment]
> This is probably because of rust-lang-nursery/rustfmt@5d9f5aa, which replaces --write-mode with --emit.

Yep, made a PR which fixes this (though there may be a better way of doing it)

https://github.com/rust-lang/rust.vim/pull/213

**Comment by abbec** [comment]
I have the same issue
