### ISSUE TITLE
Signs not showing with syntastic and rust 1.28.0

### ISSUE THREAD

**Issue by hsabouri** [rust-lang/rust.vim#214]
I can't get the signs or highlighting working to work without the location list. It works well with other languages such as C. I tried Rust nightly and stable.

Here's the relevant part of my `.vimrc`

     set statusline+=%#warningmsg#
     set statusline+=%{SyntasticStatuslineFlag()}
     set statusline+=%*
     
     let g:syntastic_always_populate_loc_list = 1
     let g:syntastic_cpp_check_header = 1
     let g:syntastic_auto_loc_list = 0
     let g:syntastic_check_on_open = 1
     let g:syntastic_check_on_wq = 0
     let g:syntastic_enable_signs=1
     let g:syntastic_rust_checkers = ['cargo']

I couldn't make it work with the other issues about this problem.

**Comment by da-x** [comment]
Hi,

It may be that this is related to the problem where rust.vim's syntastic integration was too sensitive to the Vim current directory, thus it didn't match the pathnames in the errors to the pathnames of the open buffers.

I've done some changes in the master branch - can you please test to see if it fixes your issue? Thanks!

**Comment by hsabouri** [comment]
Well it works ! Thank you, I still have no idea what happened...
