### ISSUE TITLE
The contextual "dyn" keyword is not recognized

### ISSUE THREAD

**Issue by cuviper** [rust-lang/rust.vim#219]
With the new `dyn Trait` syntax in Rust 1.27, rust.vim doesn't recognize `dyn` as a keyword.

Since it's contextual, I looked up where [`dyn` is parsed](https://github.com/rust-lang/rust/blob/3eda71b00ad48d7bf4eef4c443e7f611fd061418/src/libsyntax/parse/parser.rs#L1585-L1592):

```rust
        } else if self.check_keyword(keywords::Dyn) &&
                  self.look_ahead(1, |t| t.can_begin_bound() &&
                                         !can_continue_type_after_non_fn_ident(t)) {
            self.bump(); // `dyn`
            // Always parse bounds greedily for better error recovery.
            let bounds = self.parse_ty_param_bounds()?;
            impl_dyn_multi = bounds.len() > 1 || self.prev_token_kind == PrevTokenKind::Plus;
            TyKind::TraitObject(bounds, TraitObjectSyntax::Dyn)
```

And here's the source for [`can_begin_bound`](https://github.com/rust-lang/rust/blob/3eda71b00ad48d7bf4eef4c443e7f611fd061418/src/libsyntax/parse/token.rs#L313-L317) and [`can_continue_type_after_non_fn_ident`](https://github.com/rust-lang/rust/blob/3eda71b00ad48d7bf4eef4c443e7f611fd061418/src/libsyntax/parse/parser.rs#L403-L411).

**Comment by cuviper** [comment]
Thanks @da-x!

**Comment by Intellijoule** [comment]
Sure!
[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
06/26/18,
2:58:17 PM

*​["Date"*->
​​
,
*"Project"*->
​​
,
*"Items"*->,
*"Task"*->*, *
*"Entities"*->,
*"Emails"*->,
*"Phones"*->,
*"Locations"*->*,*
*"Notes"*->,
*"Websites"*->,
*"Related to Items"*->*,* *]*



The contents of this message are private-confidential not to acted on or
given to anyone excepting the intended recipient unless an authorized
sender permits such. References such as 'me', 'I', 'we', 'ours', mine,
charles@intellijoule.com  are to be interpreted as Intellijoule, Inc and
originating from Charles@intellijoule.com, CEO as an officer of
Intellijoule, Inc. and not Charles Nutter, personally.  Do not forward,
print, copy or modify in any way the contents of this message without
written permission.
