### ISSUE TITLE
screen redrawing issue

### ISSUE THREAD

**Issue by axionix** [rust-lang/rust.vim#22]
There is a very annoying issue with VIM not redrawing on certain TERM values with a dark background after returning from :RustRun. According to the VIM experts,

"this only happens with :! and :shell. use system() instead.  This will avoid the curses mucking that results in the required redraw."

**Comment by dudelson** [comment]
I am also experiencing this issue. Using uxvrt and solarized dark theme. Is there something I can put in my .vimrc as a temporary fix?
