### ISSUE TITLE
Syntax checking breaks on a nightly crate

### ISSUE THREAD

**Issue by SephVelut** [rust-lang/rust.vim#220]
I don't know if this should be files here or cargo or the crate author or rustfmt. I just know that when I hit save on a buffer, rust.vim would highlight syntax problems including unused variables. I don't have syntastic installed on my vim so I don't know how that was working but it was.

But when I `cargo +nightly build` a project with the crate mocktopus = "~0.4" it just stops all syntax checking in that project. Completely stops until I remove the target directory. Then it works again. I don't understand enough to give a better problem case. I don't get how installing a crate can break this plugin or rustfmt? or rustc?

**Comment by da-x** [comment]
Hi! Thanks for reporting an issue.

I'm pretty sure that rust.vim does not do syntax checking on its own. Maybe some other syntax checker - ALE or LanguageClient-neovim are installed?

**Comment by SephVelut** [comment]
I'll look into it. Its possible this is related to ALE. If I don't find anything I'll close the issue
