### ISSUE TITLE
No MacVim mappings should be made when not on MacVim

### ISSUE THREAD

**Issue by orlp** [rust-lang/rust.vim#228]
Template isn't really relevant here. The issue is that rust.vim creates `<D-R>` and `<D-r>` mappings even when not on MacVim: https://github.com/rust-lang/rust.vim/blob/0d64769fd79146c9b4aea88325d2dcc3a9d448ef/ftplugin/rust.vim#L149

This interrupts my workflow because I have `<` bound to `<<` for easy re-indenting, but after introducing the mapping `<D-R>` in a non-MacVim instance, it gets interpreted as-is (rather than a control code), and thus `<` is now ambiguous between `<` and `<D-R>`.

**Comment by da-x** [comment]
I removed the Mac bindings altogether - they are too specific.
