### ISSUE TITLE
`rustfmt` is clobbering deleted buffer content

### ISSUE THREAD

**Issue by dpc** [rust-lang/rust.vim#229]
* rust.vim version: Current, vim-plug 

Sometime recently, around the time `rustfmt` version autodetection and fixing `--emit` flags, `rustfmt` started to clobber deleted buffer content.

If I open to two tabs with a different file in each, do `dd` to delete a line, then `:bnext` and `p` to paste, instead of the line I've deleted, I'm going to paste the content of the whole previous file, instead of what I've wanted. After some debugging, I've figured it out - I have `rustfmt` on save enabled, and save on buffer switch enabled. So every time I switch a tab, my deleted buffer is replaced with something `rustfmt` is doing.

If I disable `rustfmt`, the problem is gone.

**Comment by da-x** [comment]
Yes, seems I indeed insert a bug, but looks like an easy one. 

I pushed a fix to the master branch, try it out.

**Comment by dpc** [comment]
@da-x Fixed. You are my personal hero. :)
