### ISSUE TITLE
:RustFmt does not honor my rustfmt.toml

### ISSUE THREAD

**Issue by KillTheMule** [rust-lang/rust.vim#232]
Today, I've upgraded my rust.vim (I'm sorry, I don't know what version it was before.. I remember the plugin manager telling me that there were 100 changes, that's probably the number of commits?), and now `:RustFmt` does not honor my `rustfmt.toml`. I can easily see this since I use an indentation of 2, instead of the default 4. It works fine when running `rustfmt` from the command line.

Not sure what to tell about it. I've made sure that `:pwd` shows the project directory (which contains `rustfmt.toml`), but I'm not sure that's actually neccessary. Other than "it worked before", I can say that I'm using neovim-0.3.1.-dev (if you need the actual commit, let me know). I'm also using `language-client-neovim` with RLS and `rusty-tags`. I'll refrain from posting my full config, but if it is helpfull, I'd surely do so.

If there's anything else I should do or provide, please let me know!

Thanks for providing this very helpfull plugin.

**Comment by da-x** [comment]
Seems I caused this awhile doing other fixes. The execution via rustfmt now uses a tempfile, so it didn't pick on where the configuration is located.

Please tell if master fixes it now (it passed the right `--config-path` automatically).

**Comment by KillTheMule** [comment]
I works now, thanks a lot!
