### ISSUE TITLE
rustfmt-nightly requires some changes

### ISSUE THREAD

**Issue by faulesocke** [rust-lang/rust.vim#237]
Hey,

I'm encountering issues with rustfmt-nightly. It seems that rustfmt-nightly is checking all the submodules defined via the mod keyword and errors out if it can't find one of those modules. This is always the case with rust.vim, since the buffer is written to a temporary directory without all the other files. rustfmt-nightly seems to support this, but only if the input is piped directly into `rustfmt`. In this case, the formatted file is written to stdout.

* rust.vim version: recent git version (2fb3df5c53770d7710d0171a6d5ea7767f86bce9)

Steps to reproduce:
Write this code:
```
mod foobar;

fn main() {}
```

And run `:RustFmt`.

Expected vs. actual behavior:
I expect that the current buffer is formatted with rustfmt however I get the error message:
```
src/main.rs|1 col 5| error[E0583]: file not found for module `foobar`
```

**Comment by faulesocke** [comment]
Ah rustfmt version:
```
% rustfmt --version
rustfmt 0.8.2-nightly ( )
```

If you know some version which doesn't have the new behaviour, please let me know so that I can downgrade as a temporary workaround.

**Comment by da-x** [comment]
Also reported as #235 . I am testing a version that uses stdin/stdout, and it appears to work correctly in this case. However, for `RustFmtRange` we would need something different. One option is not to pass the range to rustfmt, but to give it only part of the buffer in stdin, adjusting for indentation after receiving the output.

**Comment by faulesocke** [comment]
Ah, haven't seen that one.
