### ISSUE TITLE
Doc comment syntax hightlighting with indented comments.

### ISSUE THREAD

**Issue by davidtwco** [rust-lang/rust.vim#239]
Code highlighting within doc comments was added with #63 and is fantastic. However, it seems like this highlighting does not apply to doc comments that are indented - the comment from #63 says that this should work, but for some reason it isn't for me.

For example, the following will not be highlighted:
```rust
// start of struct...

    /// This is an example.
    ///
    /// ```rust
    ///  extern crate failure;
    ///
    ///  fn main() -> Result<(), failure::Error> {
    ///     Ok(())
    ///  }
    /// ```
    pub fn builder<'a>(x: &'a str) -> Example<'a> {
        // ...code..
    }

// ..rest of struct
```

But, if the indentation is removed, then it will, like the following example:
```rust
// start of struct...

/// This is an example.
///
/// ```rust
///  extern crate failure;
///
///  fn main() -> Result<(), failure::Error> {
///     Ok(())
///  }
/// ```
    pub fn builder<'a>(x: &'a str) -> Example<'a> {
        // ...code..
    }

// ..rest of struct
```

To reproduce this, run the following in a container (`docker run -it --rm ubuntu /bin/bash` - not strictly required but helped make sure it wasn't my own configuration):
```
cd
apt update && apt install -y vim wget 
mkdir -p .vim/syntax/
wget https://raw.githubusercontent.com/rust-lang/rust.vim/master/syntax/rust.vim -O .vim/syntax/rust.vim
wget https://raw.githubusercontent.com/seanmonstar/reqwest/master/src/client.rs -O test.rs
vim test.rs
```

I see the code inside doc comments (lines 23-33) that have no indentation being highlighted but those with indentation (lines 191-207) not being highlighted. I'm using the master as of writing (2fb3df5).

**Comment by chris-morgan** [comment]
Sorry, that was my fault; I missed a place. Not sure how that happened, since I *did* check it was working. Maybe I made some other change after that that then broke it. Ah well, it’s working now.

Thanks for the report.
