### ISSUE TITLE
Buffer switching is slow with `rust.vim` 

### ISSUE THREAD

**Issue by dpc** [rust-lang/rust.vim#24]
After adding `rust.vim` to my vim suite buffer switching with `:bnext` / `:bprevious` gets annoyingly slow. It takes around a second for the new buffer to be redrawn.

**Comment by IanConnolly** [comment]
@dpc Is this still an issue for you? I can help you triage if so.

**Comment by dpc** [comment]
It's not a problem anymore, but the syntax highlighting for Rust is still slow.

**Comment by IanConnolly** [comment]
Not seeing this issue myself, have you tried profiling? (`:help profile`)

**Comment by dpc** [comment]
Yes, I did, but I've failed to pin point what's the problem. https://users.rust-lang.org/t/vim-with-rust-syntax-highlighting-enabled-slow/2397

**Comment by da-x** [comment]
@dpc, just a shot in the dark, but have you tried `set regexpengine=1` ?

**Comment by dpc** [comment]
@da-x I wasn't aware of that option. However the problem is no longer here, and I've forgotten about it. Thanks for help anyway. If it reappears, I'll try it out.
