### ISSUE TITLE
Non-code segment in doc comment highlighted as code

### ISSUE THREAD

**Issue by jonhoo** [rust-lang/rust.vim#242]
Consider the following Rust doc comment:
```rust
/// ```console
/// $ foo
/// ```
///
/// Hello world
```

With the latest `master` (a247c383ad35de70e1d0481041b2c63dec5d47da), `$ foo` is correctly not highlighted as Rust code, but "Hello world" *is* highlighted as Rust code, not as a doc comment any more. I suspect this is because

```rust
/// ```console
```

is ignored (since it doesn't start a *Rust* code block), and then the *terminating*

```
/// ```
```

is counted as *starting* a Rust code block.

**Comment by jonhoo** [comment]
Worse yet, this persists until later in the buffer. With

```rust
/// ```console
/// $ foo
/// ```
///
/// Hello world
fn foo () {}

/// ```
/// fn foo() {}
/// ```
///
/// Also world
///
/// ```
/// fn bar() {}
/// ```
fn bar() {}
```

None of the actual Rust doc comment code segments get highlighted as Rust, and all the non-code segments get highlighted.

**Comment by jonhoo** [comment]
Sorry if that came across as overly critical. I think this is generally an awesome feature; I was just short on time when filing! :)

**Comment by da-x** [comment]
Hi Jon, try the master branch now please?

**Comment by jonhoo** [comment]
Yup, that does it! Thanks!
