### ISSUE TITLE
Rust highlighting conflicts with other highlightings with custom region highlight groups

### ISSUE THREAD

**Issue by andreyorst** [rust-lang/rust.vim#243]
**rust.vim** version: 2fa74427456a68e9e90f542567f851df50d48a8c

## Steps to reproduce:
Add custom region highlight groups as [described here](http://vim.wikia.com/wiki/Different_syntax_highlighting_within_regions_of_a_file). I've used a function way.

## Expected vs. actual behavior:
I've created groups for different languages, because I write notes in markdown files that can contain different language snippets. And when rust.vim is on, all other regions use rust's highlighting.

Plugin off:
![image](https://user-images.githubusercontent.com/19470159/42903556-e17b7394-8ada-11e8-8a02-3596edfbc4bc.png)

Plugin on:
![image](https://user-images.githubusercontent.com/19470159/42903592-01701fa6-8adb-11e8-9714-de0eeb94d4c1.png)

But if I reorder blocks, it will work normal until it reaches block with rust:
![image](https://user-images.githubusercontent.com/19470159/42903647-3554975c-8adb-11e8-854a-ed13fb849576.png)

`:RustInfo`:
```vim
rust.vim Global Variables:

let g:ftplugin_rust_source_path = v:null
let g:loaded_syntastic_rust_cargo_checker = v:null
let g:loaded_syntastic_rust_filetype = v:null
let g:loaded_syntastic_rust_rustc_checker = v:null
let g:rust_bang_comment_leader = v:null
let g:rust_cargo_avoid_whole_workspace = v:null
let g:rust_clip_command = v:null
let g:rust_conceal = v:null
let g:rust_conceal_mod_path = v:null
let g:rust_conceal_pub = v:null
let g:rust_fold = v:null
let g:rust_last_args = v:null
let b:rust_last_args = []
let g:rust_last_rustc_args = v:null
let b:rust_last_rustc_args = []
let g:rust_original_delimitMate_excluded_regions = v:null
let g:rust_playpen_url = v:null
let g:rust_prev_delimitMate_quotes = v:null
let g:rust_recent_nearest_cargo_tol = v:null
let g:rust_recent_root_cargo_toml = v:null
let g:rust_recommended_style = v:null
let g:rust_set_conceallevel = v:null
let g:rust_set_conceallevel=1 = v:null
let g:rust_set_foldmethod = v:null
let g:rust_set_foldmethod=1 = v:null
let g:rust_shortener_url = v:null
let g:rustc_makeprg_no_percent = v:null
let g:rustc_path = v:null
let g:rustfmt_autosave = 0
let g:rustfmt_autosave_because_of_config = v:null
let g:rustfmt_autosave_if_config_present = v:null
let g:rustfmt_command = 'rustfmt'
let g:rustfmt_emit_files = 0
let g:rustfmt_fail_silently = 0
let g:rustfmt_options = ''
let g:syntastic_extra_filetypes = ['rust']
let g:syntastic_rust_cargo_fname = v:null
rustfmt 0.6.1-stable (49279d7 2018-05-08)

rustc 1.27.1 (5f2b325f6 2018-07-07)

cargo 1.27.0 (1e95190e5 2018-05-27)


NVIM v0.3.1-187-gcd6e7e8cf
Build type: RelWithDebInfo
LuaJIT 2.0.5
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -Wconversion -O2 -g -DMIN_LOG_LEVEL=3 -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -Wno-array-bounds -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/home/andreyorst/.cache/yay/neovim-git/src/neovim-git/build/config -I/home/andreyorst/.cache/yay/neovim-git/src/neovim-git/src -I/usr/include -I/home/andreyorst/.cache/yay/neovim-git/src/neovim-git/build/src/nvim/auto -I/home/andreyorst/.cache/yay/neovim-git/src/neovim-git/b
Compiled by andreyorst@v5-572g

Features: +acl +iconv +jemalloc +tui 
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info

```

**Comment by da-x** [comment]
Using `vim-markdown` under `NVIM v0.3.0` it works correctly for me, I've tested C highlighting after Rust:

![image](https://user-images.githubusercontent.com/321273/42904266-1c84bf84-8add-11e8-9044-33a93e6289c1.png)

So I'm guessing your problem relates to how you specifically implemented custom highlight groups, and perhaps vim-markdown does something that you can adopt.

**Comment by chris-morgan** [comment]
A helper I use to assist with debugging things like this:

```vim
func! PrintSyntaxStack()
	for id in synstack(line("."), col("."))
		echo synIDattr(id, "name")
	endfor
endfunc

map <F8> :call PrintSyntaxStack()<CR>
```

Save as ~/.vim/plugin/synprint.vim or similar, then press F8 to see what’s going on.

**Comment by andreyorst** [comment]
> Using vim-markdown under NVIM v0.3.0 it works correctly for me, I've tested C highlighting after Rust:

Which one?
1. [vim-markdown](https://github.com/SpaceVim/vim-markdown)
2. [vim-markdown](https://github.com/gabrielelana/vim-markdown)
3. [vim-markdown](https://github.com/tpope/vim-markdown)
4. [vim-markdown](https://github.com/plasticboy/vim-markdown)

I tend not to use vim-plugins if I don't really need them. Currently I'm satisfied with neovim's default markdown support. And this isn't just a markdown files problem, it is problem in general. It will occur in other filetypes as well. 

# 

I digged in, and figured out that there is `keepend` option to `:syntax region` (see `:h syn-region), which is missing on the wiki page, but adding it to the function fixes the issue for me. Interestingly enough that other languages work well without adding this parameter, so there still may be some issue with `rust-vim` somewhere.

**Comment by da-x** [comment]
Maybe the wiki needs to be updated :)

I checked, and only `tpope/vim-markdown` and `plasticboy/vim-markdown` seem to provide syntax highlighting for fenced code (the latter enables them by default), and they both do that correctly even if other languages are fenced after Rust.

Perhaps it has something to do with rust.vim's support for highlighting Rust inside Rust's own comment blocks? It's a two level nested highlighting. Maybe try reverting those changes with `git revert --no-edit 2fa744274  ced8e2f  b508cb14  95c6aba7f` and see what happens?

**Comment by andreyorst** [comment]
> Maybe try reverting those changes with `git revert --no-edit 2fa744274 ced8e2f b508cb14 95c6aba7f`

Yes this solves issue completely, even without `keepend` option in `syntax` command.

**Comment by da-x** [comment]
Alternatively, if you try different markers than ```, for example %%%, does it also solve the issue?

**Comment by andreyorst** [comment]
> Alternatively, if you try different markers than ```, for example %%%, does it also solve the issue?

No, I've tried that in the first place.

![image](https://user-images.githubusercontent.com/19470159/42927587-9779802a-8b3d-11e8-9828-f41f527aa953.png)

**Comment by da-x** [comment]
Ok, I took `TextEnableCodeSnip` as-is from the wiki and added the following in `after/syntax/markdown.md`, without any additional plugin:

```vim
call TextEnableCodeSnip('c'   , '```c',   '```', 'SpecialComment')
call TextEnableCodeSnip('rust', '```rust', '```', 'SpecialComment')
```

![image](https://user-images.githubusercontent.com/321273/42928250-731031be-8b3f-11e8-8e91-5418b30046c0.png)

And it worked correctly. What am I missing?

**Comment by andreyorst** [comment]
@da-x I've modified wiki page already: now it contains `keepend`. So to reproduce what I've encountered try to disable it.

**Comment by da-x** [comment]
Ah ok, good :)

Maybe some Vimscript expert such as @tpope can hint on whether `keepend` is crucial for two-level `syntax include` nesting? I see he's using it in `vim-markdown`.

**Comment by andreyorst** [comment]
I've also noticed, that calling functions in different order gives different results.
```vim
call TextEnableCodeSnip('rust', '```rust', '```', 'SpecialComment')
call TextEnableCodeSnip('c', '```c', '```', 'SpecialComment')
```
![image](https://user-images.githubusercontent.com/19470159/42929188-fd24e438-8b41-11e8-8d96-694f387f7abf.png)

Now, with call for C before rust:
```vim
call TextEnableCodeSnip('c', '```c', '```', 'SpecialComment')
call TextEnableCodeSnip('rust', '```rust', '```', 'SpecialComment')
```
![image](https://user-images.githubusercontent.com/19470159/42929215-130ff5b2-8b42-11e8-88cc-2fc9b51cea69.png)

Notice how `fn` changes color.

**Comment by andreyorst** [comment]
so far I've didn't encountered any issues with `keepend`, so I think that this gonna be the fix for this issue.
