### ISSUE TITLE
Opening multiple buffers causes rustfmt on save to become slow

### ISSUE THREAD

**Issue by Marwes** [rust-lang/rust.vim#245]
* rust.vim version: a247c383ad35de70e1d0481041b2c63dec5d47da

Steps to reproduce: Save a file with rustfmt on save enabled.

Expected vs. actual behavior: (neo)vim seems to try and write to disk multiple times judging from the disk activity. I'd expect only a single write to happen. Opening multiple files seems to increase the number of writes done so perhaps all currently opened buffers are formatted and written to disk?

This happens in both vim and neovim (but neovim becomes slower quicker)

```
rust.vim Global Variables:

let g:ftplugin_rust_source_path = v:null
let g:loaded_syntastic_rust_cargo_checker = v:null
let g:loaded_syntastic_rust_filetype = v:null
let g:loaded_syntastic_rust_rustc_checker = v:null
let g:rust_bang_comment_leader = v:null
let g:rust_cargo_avoid_whole_workspace = v:null
let g:rust_clip_command = v:null
let g:rust_conceal = v:null
let g:rust_conceal_mod_path = v:null
let g:rust_conceal_pub = v:null
let g:rust_fold = v:null
let g:rust_last_args = v:null
let b:rust_last_args = []
let g:rust_last_rustc_args = v:null
let b:rust_last_rustc_args = []
let g:rust_original_delimitMate_excluded_regions = v:null
let g:rust_playpen_url = v:null
let g:rust_prev_delimitMate_quotes = v:null
let g:rust_recent_nearest_cargo_tol = v:null
let g:rust_recent_root_cargo_toml = v:null
let g:rust_recommended_style = v:null
let g:rust_set_conceallevel = v:null
let g:rust_set_conceallevel=1 = v:null
let g:rust_set_foldmethod = v:null
let g:rust_set_foldmethod=1 = v:null
let g:rust_shortener_url = v:null
let g:rustc_makeprg_no_percent = v:null
let g:rustc_path = v:null
let g:rustfmt_autosave = 1
let g:rustfmt_autosave_because_of_config = v:null
let g:rustfmt_autosave_if_config_present = v:null
let g:rustfmt_command = 'rustfmt'
let g:rustfmt_emit_files = 1
let g:rustfmt_fail_silently = 0
let g:rustfmt_options = ''
let g:syntastic_extra_filetypes = ['rust']
let g:syntastic_rust_cargo_fname = v:null
rustfmt 0.8.2-nightly (5e59925 2018-07-02)

rustc 1.29.0-nightly (12ed235ad 2018-07-18)

cargo 1.29.0-nightly (af9e40c26 2018-07-05)


NVIM v0.2.2
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: /nix/store/4r5kszyy0iirc5agfah45lvz7mnnsrb4-gcc-wrapper-7.3.0/bin/gcc -Wconversion -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -I/build/source/build/config -I/build/source/src -I/nix/store/76rnm9q9y5ja4pxj84h0pyim320vlihr-libuv-1.19.2/include -I/nix/store/h4s5w59nsnvc3d5xs5jjmmjyvzkz0n2s-libmsgpack-2.1.5/include -I/nix/store/c9jmn5dd955zigj9czfwlp58a4fm43cc-unibilium-2.0.0/include -I/nix/store/bxa8yy7xb4b44a85knplybibxbjvqb3h-libtermkey-0.20/include -I/nix/store/x140lpahjmp9i54isa3mfc57j2dmbrj3-neovim-libvterm-2017-11-05/include -I/nix/store/nr3har95xnnr2ip8yx01s7gbj753njvx-jemalloc-5.0.1/include -I/nix/store/fn2x7v3bs305xl55ynj698mjc0yfn1lh-glibc-2.26-131-dev/include -I/build/source/build/src/nvim/auto -I/build/source/build/include
Compiled by nixbld

Features: +acl +iconv +jemalloc +tui 
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/nix/store/8q7phn3alha1jkf7lazad4pwdjg4jgaj-neovim-unwrapped-0.2.2/share/nvim"

Run :checkhealth for more info
```

**Comment by da-x** [comment]
I was not able to reproduce (on Vim 8.1). Opened 3 modified files, using the `:w` command only one of them is reformatted and saved. Using the `:wa` command all of them are reformatted and saved. I observed the files' modification time using `stat` in another terminal.

Are you sure that your save function is not mapped to `:wa`?

**Comment by Marwes** [comment]
> Are you sure that your save function is not mapped to :wa?

I have tried with a .vimrc/init.vim that only contain rust.vim and what is needed to get format on save running and it still happens :/

It does not seem that the files actually get updated on disk (judging from the file modification time) but there is definitely some disk related activity going on. It does not seem to matter whether the other opened buffers are modified or not either.

**Comment by da-x** [comment]
Opened about a 1,000 `.rs` files, modified the first one using ':w' with autofmt on, and it was fast.

At this point if it was my system I would attach `strace` on the vim or neovim process to see what it is doing. Also, does it happen if you open many files of other types? Perhaps it's not related to rust.vim?

Note that the execution of `rustfmt` is synchronous - perhaps `rustfmt` opens a lot of file in the process of reformatting a single one? Would be unrelated to the number of files opened in Vim, though.

**Comment by Marwes** [comment]
Some more symptoms.

* Undo(ing) past a save point requires multiple undos.
* The slowdown happens in the same way on vim 8.1 (as in neovim) but 7.x does not seem (as) affected
* Currently using Linux Mint but I have also seen this on Windows with neovim.

> Also, does it happen if you open many files of other types?

It is only .rs files that increases the slowdown, other files do not affect it.

> Perhaps it's not related to rust.vim?

Maybe, but rust.vim is the only constant I have been able to determine and I am aware that changes to the rustfmt integration has happened here as well.

I have tried to bisect rust.vim but there are a lot of commits where formatting do not work so narrowing it down is difficult. 1ee53c1daa9a9b7f74596ffc19fb4c7230c238fd does not have the behavior at least.

**Comment by Marwes** [comment]
I will try to revert some suspect commits later to see if I can figure which is the culprit

**Comment by compressed** [comment]
I can confirm the behavior @Marwes is describing here. When I have multiple files open for a while, probably some undos and other things, whenever I save (and therefore run rustfmt) it takes more time than usual as it seems to be running through all the opened files.

**Comment by da-x** [comment]
I think I figured this one out. Please see if the fix in master fixes it.

**Comment by Marwes** [comment]
Fixed by https://github.com/rust-lang/rust.vim/commit/e2cf315fb89dfcc3050da1a885129b1baa7f4889
