### ISSUE TITLE
Highlight all types from Rust Standard Library

### ISSUE THREAD

**Issue by zachwhaley** [rust-lang/rust.vim#249]
* rust.vim version: rust.vim version built with NeoVim v0.2.2 "Last Changed" date in rust.vim file is Feb 24, 2016

Common Standard types like Vec and String are highlighted, yet less common types like VecDeque and OsString are not.

**Comment by chris-morgan** [comment]
Only prelude types are highlighted. Adding other types from the standard library but *not* highlighting other types from *outside* the standard library is not useful—there’s nothing special about types in libstd beyond the prelude that would warrant special highlighting for them. Highlighting all types is the subject of #142. Closing in favour of that.
