### ISSUE TITLE
Allow disabling ctags/rust and tagbar integration

### ISSUE THREAD

**Issue by rbtying** [rust-lang/rust.vim#256]
If you're using ctags with Rust support, it's likely that you don't want to use the regex-based Rust ctags in rust.vim (and you might want a different Rust tagbar integration). There should be an option to disable both of these.

* rust.vim version: vim-plug; master

Steps to reproduce:

Have rust-vim, tagbar, and Universal ctags installed. Attempt to open tagbar -- an error come up, since the tagbar configuration for the regex-based ctags doesn't match the tagbar configuration needed by universal ctags.

**Comment by rbtying** [comment]
oops. looks like https://github.com/rust-lang/rust.vim/pull/255 fixes this.

**Comment by da-x** [comment]
#255 was merged.

**Comment by da-x** [comment]
I've made some changes now, that if you're using Universal Ctags, it should just work out of the box.
