### ISSUE TITLE
Incorrect highlighting of multiline string literals inside of doc comments

### ISSUE THREAD

**Issue by dtolnay** [rust-lang/rust.vim#258]
```
//! Check out this multiline string literal:
//!
//! ```
//! fn main() {
//!     println!("line one
//!         line two
//!         line three");
//! }
//! ```
```

The `//!` or `///` contained within the quotes of a multiline string literal are highlighted as part of the string literal. Rustdoc does not treat them as part of the string literal.

![selection_111](https://user-images.githubusercontent.com/1940490/44995138-8f3d2f00-af56-11e8-8dfe-6a5e701db485.png)

![selection_113](https://user-images.githubusercontent.com/1940490/44995150-9401e300-af56-11e8-8039-9b492a388bb3.png)

I am running current master: e2b16e28e9eefe29e1fb6aae2f36f34a39404cd8

**Comment by chris-morgan** [comment]
I [noted this as a limitation](https://github.com/rust-lang/rust.vim/issues/63#issuecomment-403266142) when we implemented this highlighting. I don’t believe we can fix this without regressing other admittedly less common cases (*viz.* `/^\s*\/\/[!\/]/` inside a multiline string inside a doc comment is not necessarily a doc comment marker), or a *vast* increase in the complexity of that functionality (to have a different syn-include of rust.vim for every type of leading marker, each with its own multi-line string rule handling *just that* leading marker) which consequently slow it down at least a little, which I am unwilling to do unnecessarily.

Others are welcome to consider the problem and experiment with implementations, but for now at least I declare it WONTFIX.
