### ISSUE TITLE
plugin doesn't seem to work?

### ISSUE THREAD

**Issue by MarkSwanson** [rust-lang/rust.vim#262]
* rust.vim version:  github master, enabled via pathogen

:set filetype?
filetype=rust

:set runtimepath?
runtimepath=~/.vim,~/.vim/bundle/YouCompleteMe,~/.vim/bundle/ale,~/.vim/bundle/html5.vim,~/.vim/bundle/poppy.vim,~/.vim/bundle/rust.vim,~/.vim/bundle/vim-airline,~/.vim/bundle/vim-airline-themes,~/.vim/bundle/vim-easyclip,~/.vim/bundle/vim-jav
ascript,~/.vim/bundle/vim-repeat,/var/lib/vim/addons,/usr/share/vim/vimfiles,/usr/share/vim/vim81,/usr/share/vim/vimfiles/after,/var/lib/vim/addons/after,~/.vim/bundle/rust.vim/after,~/.vim/bundle/vim-javascript/after,~/.vim/after

vim 8.1 - patch 209
rustc 1.30.0-nightly (f7202e40f 2018-08-27)

Expected vs. actual behavior:

:RustFmt
expected: format stuff
actual: Not an editor command: RustFmt

Paste debugging info from the Rust Vim plugin via _one_ of the following
commands: `:RustInfo`,  `:RustInfoToClipboard`, or `:RustInfoToFile <filename>`.

:RustInfo

== Not an editor command: RustInfo

*EDIT* :Cargo build works fine, so the plugin seems to be at least partially working?

**Comment by da-x** [comment]
Most likely that Vim is not loading the last version, but perhaps its builtin older version instead.
Are the Rust files files having syntax highlighting enabled?

**Comment by MarkSwanson** [comment]
Yes, syntax highlighting works.
I renamed/appended .bak to all of my installed vim81/*.*rust*vim files.
That didn't seem to help. I also backed up my vim81 dir and deleted all the *rust* files, but that didn't help.

**Comment by MarkSwanson** [comment]
Also note: I installed rustfmt via rustup. It's in ~/.cargo/bin/rustfmt
$ rustfmt --version
rustfmt 0.99.2-nightly (5c9a2b6 2018-08-07)

Maybe "-nightly" is confusing the version check?

**Comment by da-x** [comment]
I have rustfmt 0.99.4-nightly installed and it works. 

Maybe you can bisect your `rust.vim` back to a version that worked, to see what broke it?

**Comment by MarkSwanson** [comment]
Glad to hear 0.99-4-nightly works for you. Narrowing it down...
I'll try to remove plugins one by one and bisect as well. Kindof in crunch mode, will have to circle back to this.

**Comment by rubberduck203** [comment]
Try setting `filetype plugin on` in your `~/.vimrc`.
https://github.com/rust-lang/rust.vim/issues/108#issuecomment-419765275

Solved the issue for me today.

**Comment by da-x** [comment]
Ok, so as I now understand both Vundle and Pathogen require the user to have some variant of `filetype plugin ...`  command (with `on`, and also with `indent`) in their vimrc in order to have fully functional plugins. So perhaps we should close this issue.

**Comment by rubberduck203** [comment]
Perhaps document it in the installation instructions first? I can submit a PR later.

**Comment by MarkSwanson** [comment]
Setting filetype plugin on in my ~/.vimrc solved this issue for me as well.
Thanks!
