### ISSUE TITLE
Error detected while processing function rustfmt#Format..<SNR>33_RunRustfmt:

### ISSUE THREAD

**Issue by robertstien** [rust-lang/rust.vim#269]
rust.vim version:5e4672c8ba490
vim version: 7.4.160

Error detected while processing function rustfmt#DetectVersion:
line    7:
E706: Variable type mismatch for: s:rustfmt_version
Error detected while processing function rustfmt#Format..<SNR>33_RunRustfmt:
line   18:
E730: using List as a String
line   28:
E484: Can't open file /tmp/vsjqkVb/2

**Comment by da-x** [comment]
Made some fixes in master, please ping if still relevant.
