### ISSUE TITLE
Support rustfmt >= 0.99.1

### ISSUE THREAD

**Issue by jberryman** [rust-lang/rust.vim#270]
I'm new to rust, and installed last night with

    $ curl https://sh.rustup.rs -sSf | sh
    $ rustup update

After installing rust.vim today, attempting to do `:RustFmt` raised

    error: toolchain 'stable-x86_64-unknown-linux-gnu' does not contain component 'rustfmt' for target 'x86_64-unknown-linux-gnu'

After some googling it seemed like the solution was to do `rustup component add rustfmt-preview`. So now I've got a newer version of rustfmt...

```
$ rustfmt --version
rustfmt 0.99.1-stable (da17b68 2018-08-04)
```

But this results in "Unrecognized option: 'write-mode'", since the flags have been changed around.

I've edited rustfmt.vim directly for now:

            return "--emit files"

**Comment by da-x** [comment]
Version 0.99.1 should have been auto-detected. What does `:echo rustfmt#DetectVersion()` return? and `: echo g:rustfmt_emit_files`?

**Comment by jberryman** [comment]
Oh sorry, what I think was happening is that I tested after installing rustfmt, but on the same vim session in which initialization and version detection ran and produced garbage since rustfmt wasn't present. Seems to all be working now.
