### ISSUE TITLE
Syntastic doesn't respect height config

### ISSUE THREAD

**Issue by sssilver** [rust-lang/rust.vim#278]
* rust.vim version: current master (248745ab0c)
## Steps to reproduce:
- in neovim's config file, write:
```vim
let g:syntastic_loc_list_height=3
```

### Expected
- Syntastic window 3 rows tall

### Actual
- Syntastic window height default

## rustinfo
`:RustInfo` doesn't work for me

**Comment by chris-morgan** [comment]
You seem to be describing a syntastic.vim bug rather than a rust.vim bug. Is this the case?

**Comment by sssilver** [comment]
Even if so, since I don't have Syntastic directly installed, I imagine rust.vim probably ships its own copy. Which kind of makes it a rust.vim problem.

**Comment by chris-morgan** [comment]
rust.vim does not include Syntastic. I know not where it may be coming from for you, but this is not a rust.vim issue.
