### ISSUE TITLE
Use user configured textwidth if it is set

### ISSUE THREAD

**Issue by phansch** [rust-lang/rust.vim#286]
rust.vim version: `rewritten-indent` branch (unrelated to the issue)

**Steps to reproduce:**

1. Create a .vimrc which sets `textwidth=80`
2. Open a Rust file
3. Run `:set textwidth` -> it's at 99

**Expected vs. actual behavior:**

I expected the textwidth not to be changed by `rust.vim`.

It seems to be set here: https://github.com/rust-lang/rust.vim/blob/1c570699a3be4a593fe13b40ab9f8edb89187439/ftplugin/rust.vim#L55

I think it makes more sense to only set it, if it is not already set.

**Comment by chris-morgan** [comment]
See the `g:rust_recommended_style` variable. Set it to zero if you don’t want this.
