### ISSUE TITLE
Plugin appears not to get loaded by neovim

### ISSUE THREAD

**Issue by dasteihn** [rust-lang/rust.vim#318]
rust.vim version: 

The issue appears to be very similar to issue 288, though I don't use the vim-css Plugin like the other guy did.

I use vimplug and rust.vim commit 9984b97
Editor is Neovim, version 0.1.7

Steps to reproduce:
Install the rust.vim and open a Rust-file

Expected vs. actual behavior:
It's expected to have working syntax highlighting. Instead, all that is highlighted for me are the brackets, everything else is treated as normal text. 

Paste debugging info from the Rust Vim plugin via _one_ of the following
commands: `:RustInfo`,  `:RustInfoToClipboard`, or `:RustInfoToFile <filename>`.

The `RustInfo`(nor similar) command appears not to be found by nvim. Yet the PlugStatus indicates that the plugin is ready to use
```
Finished. 0 error(s).
[===]

- nerdcommenter: OK
- nerdtree: OK (not loaded)
- rust.vim: OK
```

Vimrc:
```
:set number
:colorscheme torte
:set colorcolumn=81,91
:set tabstop=4
:set smarttab
:set autoindent
:set shiftwidth=4
let g:airline_powerline_fonts = 0

let mapleader = ","

call plug#begin('~/.nvim/plugged')
Plug 'scrooloose/nerdtree', { 'on':  'NERDTreeToggle' }
Plug 'scrooloose/nerdcommenter'
Plug 'rust-lang/rust.vim'
call plug#end()
```

**Comment by mhinz** [comment]
1. Nvim v0.1.7 is pretty old. There were more than 5000 patches since then.
1. Is `~/.nvim` a symlink? Because it's not a directory that Nvim checks by default. What `~/.vim` is to Vim, is `~/.config/nvim` to Nvim.
1. Use `:scriptnames` to see exactly which files got sourced.

**Comment by dasteihn** [comment]
1. That's the thing  with Debian, you have age-old stuff. The awkward thing is that the plugin stopped working from one week to another.
2. No, that's a directory. But as most installation guides portray it it's the script file destination place for plugins
3. rust.vim gets loaded

It's notable that the other plugins work, so I'm not sure if there is a problem with the plugin folders

**Comment by mhinz** [comment]
`:set filetype syntax` shows `rust` in both cases?

**Comment by dasteihn** [comment]
No, filetype appears to be something called "hercules" for `.rs` files

Ok, I'll keep that in mind. Sadly, most instructions still aim at vim primarily, maybe that's why I didn't catch that earlier.

**Comment by mhinz** [comment]
Yeah, I guess it's related to the fact that the default filetypes detected by Nvim were [updated _not_ to set the `hercules` filetype for the file extention `.rs`](https://github.com/neovim/neovim/commit/789c46934b2089782fb0115493513bd0cc6f7388#diff-44a099e40ae628aef90a28c6408a4c61L861) two years ago.

**Comment by mhinz** [comment]
What's the output of `:verb au BufRead *.rs`?

**Comment by mhinz** [comment]
I can actually reproduce it with nvim from master but a runtime from 0.1.7.

The thing is.. you have to autocmd triggering for the `.rs` extension. But.. in your case the autocmd shipped by Nvim's `filetype.vim` comes first and only then the autocmd from rust.vim. So, the second `:setfiletype` used by rust.vim won't overwrite the `hercules` filetype set by `filetype.vim`.

This behaviour changed for you since this commit: https://github.com/rust-lang/rust.vim/commit/12f549f9e4939bca53c8a87e6921a36fb143af9a

Until then, `set filetype` forced the filetype, but now `:setfiletype` won't anymore.

And for some reason, I can seem to work around that with this:

```diff
-  Plug 'rust-lang/rust.vim
+  Plug 'rust-lang/rust.vim', {'for': 'rust'}
```

Then, `rust.vim` gets sourced before `filetype.vim` (check `:scriptnames`) and so the `setfiletype hercules` fails.

**Comment by dasteihn** [comment]
The `{'for': 'rust'}` doesn't solve it for me, awkwardly.
I'm honestly surprised that using Debian *stable* causes so many trouble lately in general, as it's one of the most used distros

**Comment by mhinz** [comment]
Honestly, I haven't looked up the vim-plug code about why it changes the loading order for me, but the above-linked PR should fix the problem cleanly.
