### ISSUE TITLE
Feature Request: get type information for expressions under cursor

### ISSUE THREAD

**Issue by stephen-swensen** [rust-lang/rust.vim#324]
Hi,

I think it would be extremely useful to be able to get type information for expressions under the cursor. e.g. the type signature of a function, or the type of a variable (including things like mutability).

For reference, I believe the VSCode Rust plugin has something like this, and [F#'s vim support](https://github.com/fsharp/vim-fsharp) does too (activated by `leader<t>`, which I rather like).

I wish I could contribute to this feature, but I am new to rust and inexperienced with vim plugin development, so I fear I am not well positioned to help. In any case, I'd be interested in your thoughts on the feasibility and level of effort, as well as any implementation ideas.

Thanks!
Stephen

**Comment by chris-morgan** [comment]
This is out of scope for rust.vim; it’s in scope for whatever LSP engine and runner you choose to use, e.g. ALE has `ALEHover` which includes the type of a variable under RLS.

For a very brief explanation of why we consider that *definitely* out of scope: you need a full compiler to be able to say what type something is, which is an expensive operation, so you need something running in the background, and you don’t want to duplicate what ALE is doing (that’d lead to duplicated CPU-intensive effort, which leads to worse performance, and has contention for features in Vim).

**Comment by stephen-swensen** [comment]
Sounds fair, thanks for the explanation and tips (super helpful to orient me on my quest)!

It took some hunting and and experimentation, but I was able to get `vim-lsp` working for me using their documentation (other resources on the web were out of date or didn't work for whatever reason): https://github.com/prabirshrestha/vim-lsp/wiki/Servers-Rust

**Comment by treeshateorcs** [comment]
@stephen-swensen could you please elaborate more on how you set up type highlighting in vim? I installed vim-lsp, but couldn't find the setting
