### ISSUE TITLE
New `.await` syntax highlighting.

### ISSUE THREAD

**Issue by rubdos** [rust-lang/rust.vim#325]
Since [built-in await syntax landed in nightly](https://github.com/rust-lang/rust/pull/60586) a few days ago, it would be nice to have `.await` highlighted in vim!

**Comment by rhysd** [comment]
This issue seems already fixed. Because `await` is a new keyword since Rust2018, simply highlight it as keyword should be ok.

https://github.com/rust-lang/rust.vim/blob/e99f3f5bc60e15c488989f6208769a271ccf0e9f/syntax/rust.vim#L49

**Comment by rubdos** [comment]
Was indeed fixed in #327.
