### ISSUE TITLE
Syntax checker doesn't work

### ISSUE THREAD

**Issue by andriykohut** [rust-lang/rust.vim#33]
I have syntastic installed, it works for other filetypes. Can't get it to work with this plugin. I don't get any errors, it just doesn't work.

Here's example:
```rust
fn main() {
    let x: i32 = "test";
}
```
When I'm trying to compile, I get:
```
test.rs:2:18: 2:24 error: mismatched types:
 expected `i32`,
    found `&'static str`
(expected i32,
    found &-ptr) [E0308]
test.rs:2     let x: i32 = "test";
                           ^~~~~~
error: aborting due to previous error
```
Saving file or running `:SyntasticCheck` doesn't do anything.

Here's `:SyntasticInfo` output:
```
Syntastic version: 3.6.0-86 (Vim 704, Darwin)
Info for filetype: rust
Global mode: active
Filetype rust is active
The current file will be checked automatically
Available checker: rustc
Currently enabled checker: rustc
```

**Comment by zkanda** [comment]
Same here. Not sure how to debug this though. :)

**Comment by chris-morgan** [comment]
The syntastic syntax checker uses `-Z parse-only`, only performing parsing and no more. Introduce a syntax error and it will be glad to yell at you. This was done for a couple of reasons:

- Doing actual compilation (even with `-Z no-trans` which basically means “prove it will compile, but don’t actually compile it) is slow; often, *really* slow.
- Syntastic is used to handling executing things like `foo %` (where `%` is the filename); for Rust, that will rarely give the desired result—only for crate root files will it. Files other than the crate root file will regularly fail to compile where they would compile fine as part of the whole crate. Figuring out where and what the crate root is (necessary for better `compiler`/`makeprg` support, frankly) is not the simplest of tasks and nothing has been done about it.

**Comment by andriykohut** [comment]
Ah, makes sense. Thanks for clarifying then. Should I close this?

**Comment by wsendon** [comment]
I think this should be added to the README. I thought I did something wrong and installed syntastic and rust vim twice only to find out this page later.
