### ISSUE TITLE
writing to .rs file crashes zsh 

### ISSUE THREAD

**Issue by hkennyv** [rust-lang/rust.vim#332]
* rust.vim version: 
I'm using vim-plug to manage plugins.

vim --version
```
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Feb 22 2019 19:03:04)
```

Steps to reproduce:

1. `touch main.rs`
2. `vim main.rs`
3. make a change to `main.rs` and save the file using `:w`
4. shell crashes, giving following error:
```
[1]  + 2721 suspended (tty output)  vim main.rs
khuynh@kmbp:~ $ 
zsh: error on TTY read: Input/output error

[Process completed]
```

Expected vs. actual behavior:
Unexpected that zsh crashes. When I comment out the rust.vim plugin, writing to a `.rs` file no longer crashes zsh. Only `.rs` files crash zsh, I've tried writing to `.c`, `.py`, `.js` and vim can write without crashing.

Paste debugging info from the Rust Vim plugin via _one_ of the following
commands: `:RustInfo`,  `:RustInfoToClipboard`, or `:RustInfoToFile <filename>`.

When trying those commands, I get:

```
E492: Not an editor command: RustInfo
```

**Comment by chris-morgan** [comment]
`E492: Not an editor command: RustInfo` implies that rust.vim is not loaded. Does vim-plug defer its loading until you open a .rs file? Try opening a .rs file first.

**Comment by hkennyv** [comment]
Running a `:PlugInstall` indicates rust.vim is already installed.
![image](https://user-images.githubusercontent.com/29909203/61406763-5c133e00-a891-11e9-8d19-976b981f69f0.png)

Opening a .rs file and then running `:RustInfo` crashes my shell with the same error as trying to write to the file instead of giving the `E492: Not an editor command: RustInfo` error when I try to use the command in a non .rs file.
![image](https://user-images.githubusercontent.com/29909203/61406827-7f3ded80-a891-11e9-8697-6b3a8ef14efb.png)

So, maybe it is crashing upon loading rust.vim?

**Comment by da-x** [comment]
From browsing a bit, I think this is not really a rust.vim issue but instead related to a configuration problem with Vim and Zsh. See https://github.com/robbyrussell/oh-my-zsh/issues/4174 . Also, if you have `bash` installed as most systems these days, I would recommend adding `set shell=/bin/bash` to your Vim config. Please re-open if relevant.
