### ISSUE TITLE
Unknown option: cfg

### ISSUE THREAD

**Issue by zenixls2** [rust-lang/rust.vim#345]
* rust.vim version:  git commit f45cdae27133912e6c1c1d41c17b9613b60afe07
Steps to reproduce:

mine installation is through vim-plug.  
by changing the order of these two lines, different results will occur:  
```vim
Plug 'rust-lang/rust.vim'
Plug 'cespare/vim-toml'
```

Expected vs. actual behavior:

if vim-toml is loaded before rust.vim, no error will occur.
otherwise, vim will output something like:
```text
"Cargo.toml" 10L, 252C
Error detected while processing FileType Auto commands for "*":
E518: Unknown option: cfg
```
and vim-toml will be ignored (no color for the script).  
The error message is produced by [this line](https://github.com/rust-lang/rust.vim/blob/master/ftdetect/rust.vim#L4)
vim version is 
```text
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Sep 18 2016 14:42:40)
```

Paste debugging info from the Rust Vim plugin via _one_ of the following
commands: `:RustInfo`,  `:RustInfoToClipboard`, or `:RustInfoToFile <filename>`.

these won't work.

**Comment by mhinz** [comment]
You didn't mention the `Included patches` bit from `vim --version`, but you probably have a version older than [`8.0.0613`](https://github.com/vim/vim/commit/3e54569b1), which is the commit that introduced the `FALLBACK` syntax.

As for the order issue: When `cespare/vim-toml` is run first, it [sets the filetype to `toml`](https://github.com/cespare/vim-toml/blob/master/ftdetect/toml.vim#L2) and thus the [`:setfiletype` from this plugin](https://github.com/rust-lang/rust.vim/blob/master/ftdetect/rust.vim#L4) will return early without ever processing its arguments.

**Comment by zenixls2** [comment]
the version I used is 8.0.003-1 provided in Ghettoforge Plus repo in CentOS 7.
the default verson in main repo is at 7.4

Is there any possibility to do the version check before to prevent this issue?
Or maybe we need to add a dependency requirement of version 8.0.0613 in README.

**Comment by mhinz** [comment]
The above PR should fix it for you.
