### ISSUE TITLE
Highlighting incorrect on scroll

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust.vim#35]
For most of the tests in the rust-lang/cargo repo, if I open the file and then use `G` to go to the end of the file, the syntax highlighting ends up getting messed up. For example, when opening the file:

![https://i.imgur.com/ZixHFcN.png](https://i.imgur.com/ZixHFcN.png)

and after `G`:

![https://i.imgur.com/1Vx56Y7.png](https://i.imgur.com/1Vx56Y7.png)

**Comment by chris-morgan** [comment]
This is a Vim issue which we should not try to work around. Look at the `:syn-sync` help for more information. The default setting, shown by `:syn sync`, is likely to be “syncing starts 200 lines before top line”, so if something triggers a total redraw (which `G` often will and <kbd><kbd>Ctrl</kbd>+<kbd>L</kbd></kbd> will) and there is a multi-line string open 200 lines before the top line—line 1464 in your case of `test_cargo_compile_git_deps.rs`—it will understandably fall apart.

One solution is `syn sync fromstart`, but that is not appropriate for a filetype plugin to specify without great need. You are welcome to do it yourself, however.
