### ISSUE TITLE
Syntax highlighting breaks with box( ... )

### ISSUE THREAD

**Issue by spastorino** [rust-lang/rust.vim#355]
Open [this file](https://github.com/rust-lang/rust/blob/2e7244807a7878f6eca3eb7d97ae9b413aa49014/src/librustc_mir/transform/qualify_consts.rs) in vim using rust.vim and you will see that syntax highlighting breaks after the use of box(...). [This is the line in question](https://github.com/rust-lang/rust/blob/2e7244807a7878f6eca3eb7d97ae9b413aa49014/src/librustc_mir/transform/qualify_consts.rs#L1054).

**Comment by da-x** [comment]
Fixed. We had to remove old and irrelevant syntax highlighting rules that tried to deal with the cancelled box placement syntax.
