### ISSUE TITLE
Provide feature similar to VSCode "crates" extension

### ISSUE THREAD

**Issue by XVilka** [rust-lang/rust.vim#365]
https://marketplace.visualstudio.com/items?itemName=serayuzgur.crates

This is "crates", an extension for crates.io dependencies. Aims helping developers to manage dependencies while using Cargo.toml.

Features:
- Displays the latest version of the crate next to it
- Shows all versions (clickable) on tooltip of the crate hovered.

Would be nice to have the similar feature in vim plugin as well, when opening Cargo file.

## Update Single Dependency
![image](https://user-images.githubusercontent.com/203261/68028298-8deccb00-fcef-11e9-8350-68ad743ccbb7.png)
## Update All Dependencies (lazy mode)
![image](https://user-images.githubusercontent.com/203261/68028307-91805200-fcef-11e9-90a1-66e40fe497e1.png)

**Comment by mhinz** [comment]
I think this is out of this plugin's scope, since it requires quite a bit of code.

Anyway, I like the idea, so I plan to hack up a plugin for it!

**Comment by XVilka** [comment]
@mhinz I don't know if you are aware of [crin](https://github.com/joseluis/crin) tool, which can probably save you a lot of time and code:

![image](https://user-images.githubusercontent.com/203261/68072484-4a629180-fdc1-11e9-912d-81ce66758ab0.png)

**Comment by mhinz** [comment]
I wasn't. :) My current prototype relies on curl to get all versions. E.g.

```
curl -sLH 'Accept: application/vnd.github.VERSION.raw' https://api.github.com/repos/rust-lang/crates.io-index/contents/ca/rg/cargo_metadata | jq '.vers'
```

**Comment by mhinz** [comment]
And here it is: https://github.com/mhinz/vim-crates

**Comment by XVilka** [comment]
Closing this bug then.
