### ISSUE TITLE
rust.vim doesn't report any wrong code

### ISSUE THREAD

**Issue by silvioprog** [rust-lang/rust.vim#367]
### Environment

**OS:** Fedora 31 Workstation and GNOME.
**Terminal:** GNOME Terminal 3.34.2.
**Cargo:** Version 1.40.0-nightly.
**Racer:** Version 2.1.28.
**RustInfo:** Please see file in attachment.
**rust.vim:** Latest version installed via [vim-plug](https://github.com/rust-lang/rust.vim#installation).

Both `cargo` and `racer` are available in `$PATH`.

### VimRC

```viml
call plug#begin()
" VIM AirLine
Plug 'vim-airline/vim-airline'
" Rust
Plug 'rust-lang/rust.vim'
" Racer
Plug 'racer-rust/vim-racer'
call plug#end()

" Rust
let g:rustfmt_autosave = 1
let g:rust_clip_command = 'xclip -selection clipboard'
" Racer
let g:racer_experimental_completer = 1
let g:racer_insert_paren = 1
au FileType rust nmap gd <Plug>(rust-def)
au FileType rust nmap gs <Plug>(rust-def-split)
au FileType rust nmap gx <Plug>(rust-def-vertical)
au FileType rust nmap <leader>gd <Plug>(rust-doc)
```

### Steps to reproduce

Just open a `*.rs` file and put some wrong code, for example:

```rust
fn main() {
    printlnXXX!("test");
}
```

it was supposed to indicate the wrong `printlnXXX`, something like this (picture edited by GIMP):

![image](https://user-images.githubusercontent.com/1456829/68319822-b1bc6200-009d-11ea-853c-af9b50bbe63c.png)

but it doesn't. The following image is how it is showed for me:

![image](https://user-images.githubusercontent.com/1456829/68316813-d95cfb80-0098-11ea-8573-2a6b4702e6ad.png)

notice it doesn't make any checking.

So, is this a bug, or just missing some configuration?

Thank you!

[RustInfo.txt](https://github.com/rust-lang/rust.vim/files/3815813/RustInfo.txt)

**Comment by chris-morgan** [comment]
That sort of functionality is out of scope for this plugin. Look into something like coc.vim or ALE.
