### ISSUE TITLE
RustFmt does not take into account edition from Cargo.toml

### ISSUE THREAD

**Issue by jonhoo** [rust-lang/rust.vim#368]
* rust.vim version: 97fdc4e4975515d8e8a5a82380dd85628d59a005

Steps to reproduce:

```console
$ cargo new --bin edition-fmt
$ cd edition-fmt
$ grep edition Cargo.toml
edition = "2018"
$ echo 'fn main() { async { 1; }; }' > src/main.rs
```

Expected vs. actual behavior:

**Expected**:

Open `src/main.rs` in editor and run `:RustFmt`. The file should now look like this:
```rust
fn main() {
    async {
        1;
    };
}
```

**Actual**:

Open `src/main.rs` in editor and run `:RustFmt`. You get the error:

```
error: expected identifier, found `1`
```

This is because `rustfmt` is run, which defaults to the 2015 edition (where `async` isn't supported). The `rustfmt` command does not take into account `edition` from `Cargo.toml`. It is possible to work around this by doing:

```console
$ echo 'edition = "2018"' > rustfmt.toml
```

But remembering to do this in all projects is a bit of a pain, and is not very discoverable. I believe the reason why `rustfmt` is used over `cargo fmt` is to support formatting only certain paths, and to support formatting even when operating on Rust files not in a cargo project, but the cost here seems too high. Is there some way we can get both that functionality and have sensible support for `edition` as specified in `Cargo.toml`?

**Comment by bcmyers** [comment]
Hey @jonhoo. Nice to see we're having the same issue. I solved it by putting the following in my `.vimrc`:
```
let g:rustfmt_options = '--edition 2018'
```
This of course sets the edition globally; so it's no good if you're still working on both 2015 and 2018 projects. It's also odd that 2018 is not the default.

In any case, for a more comprehensive solution, it'd be nice to see the edition being picked up automatically from the `Cargo.toml` as you suggest.  

In the meantime, though, this seems to be working for me as I don't have any 2015 projects I'm working on.

**Comment by chris-morgan** [comment]
I think we need either a way of telling `rustfmt` to get options from Cargo.toml (as a fallback for rustfmt.toml, which I think would be acceptable still for projects that don’t use Cargo), or for `cargo fmt` to expose a means of only formatting a single file, which it doesn’t look to at present. Either way, I think this needs to be a rustfmt issue, to provide the hooks that we need. I’m too lazy right now to file such an issue myself; I invite others to.

**Comment by bcmyers** [comment]
In the meantime @chris-morgan, shouldn't whatever `rust.vim` does default to the 2018 edition? As people start using async/await, this is going to become an issue for a lot of users.

**Comment by chris-morgan** [comment]
Sounds not ideal, but overall reasonable. Patch accepted.

**Comment by alexryndin** [comment]
> Sounds not ideal, but overall reasonable. Patch accepted.

Hi, will this patch be available in master then?

**Comment by da-x** [comment]
@alexryndin I pushed to master now. @mhinz I amended your commit a bit, should work now whether rustfmt.toml exists or not.
