### ISSUE TITLE
matchit.vim fails to load with latest neovim

### ISSUE THREAD

**Issue by landaire** [rust-lang/rust.vim#38]
[`ftplugin/rust.vim`](https://github.com/rust-lang/rust.vim/blob/master/ftplugin/rust.vim#L93) will source `$VIMRUNTIME/macros/matchit.vim`  regardless of whether or not it needs to be loaded, and always assumes it's in the `macros` dir.

This is not true as of https://github.com/neovim/neovim/pull/2723/. That PR made `matchit.vim` always loaded by default and moved `matchit.vim`: `runtime/macros/matchit.vim → runtime/plugin/matchit.vim`. I believe that a solution would be to instead perform the following:

    if !exists('loaded_matchit')
        source $VIMRUNTIME/macros/matchit.vim
    endif

But I'm still relatively new to vim so I'm not really sure. This *appears* to work on my machine though.

nvim details:

```
~
❯ nvim -v
NVIM 0.0.0-alpha+201506222256 (compiled Jun 23 2015 20:42:16)
Commit: 20a57c497b55bb3632f0d4bcd76c18628cfa5f43
Build type: RelWithDebInfo
Compilation: /usr/local/Library/ENV/4.3/clang -Wconversion -O2 -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/tmp/neovim20150623-23404-1k8l993/build/config -I/tmp/neovim20150623-23404-1k8l993/src -I/tmp/neovim20150623-23404-1k8l993/.deps/usr/include -I/tmp/neovim20150623-23404-1k8l993/.deps/usr/include -I/tmp/neovim20150623-23404-1k8l993/.deps/usr/include/luajit-2.0 -I/tmp/neovim20150623-23404-1k8l993/.deps/usr/include -I/tmp/neovim20150623-23404-1k8l993/.deps/usr/include -I/tmp/neovim20150623-23404-1k8l993/.deps/usr/include -I/tmp/neovim20150623-23404-1k8l993/.deps/usr/include -I/Library/Frameworks/Mono.framework/Headers -I/usr/include -I/tmp/neovim20150623-23404-1k8l993/build/src/nvim/auto -I/tmp/neovim20150623-23404-1k8l993/build/include
Compiled by lander@uoeno.local

Optional features included (+) or not (-): +acl   +iconv    +jemalloc
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/nvimrc"
     user vimrc file: "~/.nvimrc"
 2nd user vimrc file: "~/.nvim/nvimrc"
      user exrc file: "~/.exrc"
  fall-back for $VIM: "/usr/local/Cellar/neovim/HEAD/share/nvim"
```

**Comment by martinisoft** [comment]
I have posted a pull request to resolve this issue. Ran into the same problem myself on the latest master build of Neovim.

**Comment by martinisoft** [comment]
Made the pull request inccorectly, all good to go now :+1:

**Comment by Pyrohh** [comment]
This shouldn't be an issue as of https://github.com/neovim/neovim/commit/957c81539f9be2654fdb89c319c835bdf1a2ef60.
