### ISSUE TITLE
annoying issue: open rust source file, rust.vim will trigger a cargo check, it will take long time.

### ISSUE THREAD

**Issue by xiaods** [rust-lang/rust.vim#385]
* rust.vim version:  latest
Steps to reproduce:
cd rust project
vim .
it will take some munitues to handle cargo check command.
i will waiting the check... it is annoy  me.

Expected vs. actual behavior:
don't do cargo check, but he README recommend it. how about bypaas it and later cargo check by manual.

anyone can share your prefer on this setting.

**Comment by xiaods** [comment]
any update?

**Comment by rhysd** [comment]
It doesn't reproduce on my laptop. I guess it's a problem of your environment

**Comment by xiaods** [comment]
@rhysd thanks for your reminder.
