### ISSUE TITLE
Why is tabstop set to 8?

### ISSUE THREAD

**Issue by MTBorg** [rust-lang/rust.vim#393]
Originally posted [here](https://github.com/sheerun/vim-polyglot/issues/467).

I'm using neovim 0.4.3 and rust.vim via the language pack [vim-polyglot](https://github.com/sheerun/vim-polyglot).

According to the [rust docs](https://doc.rust-lang.org/1.0.0/style/style/whitespace.html) indentation should use 4 spaces, but in ftplugin/rust.vim tabstop is set to 8
https://github.com/rust-lang/rust.vim/blob/db0137dfad4690621e01dbae780fb4a2dd7dbf27/ftplugin/rust.vim#L48-L52

This causes some code to look like
```rust
fn main(){
        println!("hello world");
}
```
when it should look like
```rust
fn main(){
    println!("hello world");
}
```

Here is my vimrc 
```vimrc
set nocompatible
set showmatch
set hlsearch 
set tabstop=2
set softtabstop=2
set noexpandtab
set shiftwidth=2
set autoindent
set number relativenumber
set cc=80
set termguicolors "Enable true colors
set updatetime=200 "This makes the git gutter update faster
set noswapfile
set numberwidth=1
set encoding=UTF-8
filetype plugin indent on
syntax on

let mapleader="§"

" Keybindings
""""""""""""""""""""""""""
	" Resource .vimrc
	nnoremap <silent> <Leader>src :source ~/.config/nvim/init.vim<CR>
	
	" NERDTree
	nnoremap <silent> <Leader>e :NERDTreeToggle<CR>

	" WhichKey
	nnoremap <silent> <Leader>? :WhichKey '§'<CR>

	" Vim-fugitive
	nnoremap <silent> <Leader>gd :Gdiffsplit<CR>
	nnoremap <silent> <Leader>gst :Gstatus<CR>
	nnoremap <silent> <Leader>gb :Gblame<CR>

	" Bind popup navigation to ctrl-j and ctrl-k
	inoremap <expr> <C-j> ((pumvisible())?("\<C-n>"):("j"))
	inoremap <expr> <C-k> ((pumvisible())?("\<C-p>"):("k"))

	" Jump window
	nnoremap <silent> <Leader>j :jumps<CR>

	" Undotree
	nnoremap <silent> <Leader>u :UndotreeToggle<CR>

	" Vim-vebugger
	nnoremap <silent> <Leader>dc :VBGcontinue<CR>
	nnoremap <silent> <Leader>de :VBGeval<Space>
	nnoremap <silent> <Leader>dbt :VBGtoggleBreakpointThisLine<CR>
	nnoremap <silent> <Leader>dbc :VBGclearBreakpoints<CR>
	nnoremap <silent> <Leader>dk :VBGkill<CR>
""""""""""""""""""""""""""

call plug#begin('~/.local/share/nvim/plugged/')
	"Color scheme
	Plug 'whatyouhide/vim-gotham' 

	"NERDTree
	Plug 'scrooloose/nerdtree', {'on': 'NERDTreeToggle' }
	Plug 'Xuyuanp/nerdtree-git-plugin'

	"Git
	Plug 'tpope/vim-fugitive'
	Plug 'airblade/vim-gitgutter'

	"Airline
	Plug 'vim-airline/vim-airline'
	Plug 'vim-airline/vim-airline-themes'

	"Tmux
	Plug 'edkolev/tmuxline.vim'
	Plug 'christoomey/vim-tmux-runner'
	Plug 'christoomey/vim-tmux-navigator'

	"Coc
	Plug 'neoclide/coc.nvim', {
		\ 'branch': 'release', 
		\ 'do': ':CocInstall coc-tsserver coc-python coc-json coc-eslint coc-prettier coc-css coc-html coc-snippets'
	\}

	"Misc
	Plug 'janko/vim-test'
	Plug 'ctrlpvim/ctrlp.vim'
	Plug 'ap/vim-css-color'
	Plug 'tpope/vim-repeat'
	Plug 'tpope/vim-commentary'
	Plug 'tpope/vim-surround'
	Plug 'Yggdroot/indentline'
	Plug 'honza/vim-snippets'
	Plug 'liuchengxu/vim-which-key', { 'on': ['WhichKey', 'WhichKey!'] }
	Plug 'mbbill/undotree'
	Plug 'mileszs/ack.vim'
	Plug 'sheerun/vim-polyglot'
	Plug 'mattn/emmet-vim'
	Plug 'idanarye/vim-vebugger', {'branch' : 'develop'}
	Plug 'Shougo/vimproc.vim', {'do' : 'make'}
call plug#end()

" Resource config when saved
augroup vimrchook
	au!
	autocmd bufwritepost $MYVIMRC source $MYVIMRC
augroup END

autocmd BufEnter *.tsx set filetype=typescript.vim

" Enable debugging
packadd termdebug

colorscheme gotham
```

And here's the output of `:verbose set tabstop?` confirming tabstop is set to 8 by the plugin
```
tabstop=8
        Last set from ~/.local/share/nvim/plugged/vim-polyglot/ftplugin/rust.vim line 52
```
which maps to these lines in vim-polyglot
https://github.com/sheerun/vim-polyglot/blob/45ab4d80dd52f6ea40d8e9b7fa5cedd31d9ad9ec/ftplugin/rust.vim#L50-L54

Also, should really the default value of `get(g:, 'rust_recommended_style', 1)` be 1? If the variable isn't set, i feel as though the default value should be to not use the default settings.

**Comment by julianandrews** [comment]
I've also run into this issue with the LSP plugin I use: https://github.com/prabirshrestha/vim-lsp.

I opened an issue there: https://github.com/prabirshrestha/vim-lsp/issues/740

For reference, the justification for the change to 8 spaces can be found here: https://github.com/rust-lang/rust.vim/commit/46bfb18bbced96387c6f7981c039fcdc2d37fee7

On reflection, I'm not sure it makes sense for `rust.vim` to set tabstop at all. I understand, and even agree with the argument for why `rust.vim` shouldn't set `tabstop=4`. That said, if you're using the recommended style guidelines, then there will be no tabs in your code. Since the setting shouldn't do anything at all if the user is following Rust guidelines, and I'm not sure I see a good reason `rust.vim` should have an opinion on the value. By leaving the value out entirely it makes it easier for the user to choose a value if they want to, and there's less chance of surprise.
