### ISSUE TITLE
Feature request: Building crate in workspace?

### ISSUE THREAD

**Issue by matthiasbeyer** [rust-lang/rust.vim#401]
Not a bug but a feature request.

It would be nice if there'd be a command to build the crate the current file belongs to. This would be helpful in a workspace environment.

For example, when I have a workspace with two crates and both of the files open in my vim instance:

```
/crate-a/src/lib.rs
/crate-b/src/main.rs
```

I'd like to be able to call something like `CargoCheckFile` while my cursor is in the buffer with `lib.rs`, rust.vim finds out which crate this belongs to and calls `cargo check --manifest-path ./crate-a/Cargo.toml`.

**Comment by da-x** [comment]
This check the current crate. You can have something like:

```
command! CargoCheckCrate call cargo#cmd("check --manifest-path ".cargo#nearestCargo(0))
```

**Comment by matthiasbeyer** [comment]
Solves my problem. Thanks! :heart:
