### ISSUE TITLE
Plugin doesn't work - Vim8 packages

### ISSUE THREAD

**Issue by bleepster** [rust-lang/rust.vim#408]
* rust.vim version: 
_master branch on Vim 8.1 (using the default vim8 plugin manager)_

Steps to reproduce:

1) Install the plugin as described in the README - under "Vim8 Packages"
2) Open a rust source file and run the formatter, `:RustFmt` 

Expected vs. actual behavior:

I should have been able to execute `:RustFmt` but instead I got _E492: Not an editor command: RustFmt_

Paste debugging info from the Rust Vim plugin via _one_ of the following
commands: `:RustInfo`,  `:RustInfoToClipboard`, or `:RustInfoToFile <filename>`.

I checked the plugin to see if it was getting picked up, by running `:help :RustFmt` and the documentation was displayed. I looked around for existing issues reported that was similar to what I encountered and came across [this](https://github.com/rust-lang/rust.vim/issues/262). The issue pointed to a different plugin manager but I decided to try the solution anyway and it worked.

Perhaps, the README should be updated to include the `filetype plugin on` as a pre-requisite under _"Vim8 Packages"_ as well.

**Comment by silvertheo** [comment]
@bleepster Thx！You solved my question！
> filetype plugin on

Input this config into the '~/.vimrc'

**Comment by 0xB10C** [comment]
This has been addressed with https://github.com/rust-lang/rust.vim/pull/412, correct?

**Comment by bleepster** [comment]
> This has been addressed with #412, correct?

Yes.
