### ISSUE TITLE
Run rustfmt on save?

### ISSUE THREAD

**Issue by kazimuth** [rust-lang/rust.vim#43]
I've been using [vim-go](https://github.com/fatih/vim-go), which has this feature, and it's really nice.

**Comment by giodamelio** [comment]
:+1:

**Comment by oblitum** [comment]
:+1: just be careful if implementing this, vim-go is one of a few plugins that implements this correctly, check this issue:

- https://github.com/fatih/vim-go/issues/40

and this comment:

- https://github.com/rhysd/vim-clang-format/issues/8#issuecomment-58316885

**Comment by beefsack** [comment]
:+1:

**Comment by IanConnolly** [comment]
Have a working version of this locally, just needs a cleanup. Will PR it in soon.

Thanks @oblitum for the vim-go reference, the code (and more importantly, the commit history), was v. useful. Didn't take much adapting to drop rustfmt in.

**Comment by filsmick** [comment]
:+1:
