### ISSUE TITLE
Does this project support neovim

### ISSUE THREAD

**Issue by Cpointerz** [rust-lang/rust.vim#441]
It doesn't seem to start after neovim is installed

**Comment by lemunozm** [comment]
Yes. I'm using neovim and it works perfectly.

Did you add: 
```vim
syntax enable
filetype plugin indent on
```
and execute the `:PlugInstall` or similar?

**Comment by Cpointerz** [comment]
But I can't work here. For example, error checking doesn't work

**Comment by lemunozm** [comment]
Do you set up [Syntastic](https://github.com/vim-syntastic/syntastic)? This plugin uses the Syntastic plugin for error checking but does not perform the Syntastic installation and configuration.

**Comment by Cpointerz** [comment]
Thank you.The problem is solved。
