### ISSUE TITLE
Parentheses and cr, need to add additional indentation

### ISSUE THREAD

**Issue by login224444** [rust-lang/rust.vim#442]
I'm using coc-pairs - which adds additional pair automatically, and because of it i'm using cr, instead of \<cr\>)O combination - which works, but that's not a point. This must be a default behavior.

Wrong behavior:

    fn some fn(<cr>)
    fn some_fn(
        x: i64
        ) <--- incorrect indentation

How to make like that:
    
    fn some fn(<cr>)
    fn some_fn(
        x: i64
    ) <--- CORRECT INDENTATION

Current options: 

    set cinoptions=L0,(s,Ws,J1,j1,m1
    set indentkeys=0{,0},!^F,o,O,0[,0],0(,0)

**Comment by YorickPeterse** [comment]
@login224444 Did you figure out how to make this work?

**Comment by login224444** [comment]
> @login224444 Did you figure out how to make this work?

Nope. I've considered just not to use automatic pairs. But problem is - automatic macros's parenetheses with autocompletion. Because with function  i can disable it with rust-analyzer's setting, but macro - not. And it's just kind of annoying, because of inconsistency experience.

**Comment by YorickPeterse** [comment]
@login224444 Ah, that's a bummer. I have the same problem (https://github.com/rust-lang/rust.vim/issues/442). I did find you can sort of work around it by having `<cr>` also run `=ko`. This however requires hacking whatever pairs plugin you use ([here's an example using nvim-autopairs](https://gitlab.com/yorickpeterse/dotfiles/-/commit/47b03afce97926b69256f6bdad0f4ebaa2218486#c95284060ef2333bd4347ae70f3d7a6a31253ff5_27_29)).
