### ISSUE TITLE
Please add a LICENSE file

### ISSUE THREAD

**Issue by edunham** [rust-lang/rust.vim#45]
Probably dual Apache + MIT like the other Rust stuff?

re: https://github.com/rust-lang/rust/issues/25664

**Comment by IanConnolly** [comment]
For what it's worth, most Vim plugins declare themselves to be distributed under the same terms as Vim itself is.

eg. https://github.com/tpope/vim-fugitive/blame/master/README.markdown#L117-L118

**Comment by jordwalke** [comment]
Any update here?

**Comment by steveklabnik** [comment]
So, we'd have to make it under apache + MIT for now, because that was what it was written under.


If we can get all of these https://github.com/rust-lang/rust.vim/graphs/contributors people to sign off on changing to the vim license, then we can change it. If we think it's worth it, we can do that work.

**Comment by jordwalke** [comment]
Is there anything wrong with Apache+MIT in the mean time?

**Comment by edunham** [comment]
@steveklabnik Thanks for clarifying that it was written under the same terms as Rust (do they apply by default to everything in the Rust org, or something?). Opened new PR to add the same licenses. 

I personally think it's more important to get an open source license into the repo than to bikeshed over which one to use.

**Comment by steveklabnik** [comment]
>  (do they apply by default to everything in the Rust org, or something?)

All the editor stuff was literally in-tree, before I split them out into separate repos, so most of the development was done in rust-lang/rust, hence the licesnse

**Comment by edunham** [comment]
Excellent. #55 landed, so this is now resolved.
