### ISSUE TITLE
Triple slash comments cannot be wrapped automatically

### ISSUE THREAD

**Issue by tbu-** [rust-lang/rust.vim#47]
Stackoverflow has [a working solution](http://stackoverflow.com/a/28078855/) for that, but I don't know how to integrate it into the files in this repository.

It says I should add this to my `.vimrc`:
```
autocmd Filetype c,cpp set comments^=:///
```
This works (after replacing `c,cpp` with `rust`), but `ftplugin/rust.vim` already adds `:///` to the set of possible comments. Moving it to the end does not help either.

**Comment by steveklabnik** [comment]
Hmmm, they wrap automatically for me.

**Comment by tbu-** [comment]
Mh. Apparantly it's due to the fact that I don't have `filetype plugin on` in my `.vimrc`. Should this be added to the readme?

**Comment by tbu-** [comment]
(Otherwise feel free to close this issue, I no longer have it since I found `filetype plugin on`.)

**Comment by tbu-** [comment]
Closing, the solution is in https://github.com/rust-lang/rust.vim/issues/47#issuecomment-139865863.
