### ISSUE TITLE
highlight and/or annotate (implicit) return expressions

### ISSUE THREAD

**Issue by zevaverbach** [rust-lang/rust.vim#470]
It'd be great if there were some indication -- via highlighting or annotating -- that a line inside a function body is an expression and thus defines the return value of the function.

[Here's a Twitter thread illustrating the "semicolon-hunting" pain this could alleviate](https://twitter.com/im_snif/status/1492142113705836545)

Happy to help contribute a PR for this if you think it's worthy.

**Comment by chris-morgan** [comment]
You can achieve this with rust-analyzer by moving the cursor to the `fn` keyword: it highlights the innermost trailing expressions that will return, and `return` and `?` keywords.

As for implementing such a feature in this plugin itself, I would call it fairly thoroughly out of scope: use rust-analyzer instead, e.g. via coc.

(Plus I see no technically feasible way of achieving similar results in pure Vimscript without major compromises, most likely to performance.)
