### ISSUE TITLE
E1126: Cannot use :let in Vim9 script

### ISSUE THREAD

**Issue by acatton** [rust-lang/rust.vim#471]
* rust.vim version: the latest master at the time of filing 4aa69b84c8a58fcec6b6dad6fe244b916b1cf830 (Tue Oct 5 20:36:15 2021 +1300), without a plugin manager.

Steps to reproduce:

1. Open a rust file (e.g `vim src/main.rs`)
2. Re-edit it (i.e. `:e` without any argument)

Expected vs. actual behavior:

The file should be re-opened, instead I get the error:

```
Error detected while processing BufRead Autocommands for "*.rs"..FileType Autocommands for "*"..function <SNR>10_LoadFTPlugin:
line    2:
E1126: Cannot use :let in Vim9 script
```

Paste debugging info from the Rust Vim plugin via _one_ of the following
commands: `:RustInfo`,  `:RustInfoToClipboard`, or `:RustInfoToFile <filename>`.

This is what `vim -V9/tmp/log` outputs:

```
line 25: sourcing "/home/acatton/.vim/pack/foobar/start/rust/after/syntax/rust.vim"
finished sourcing /home/acatton/.vim/pack/foobar/start/rust/after/syntax/rust.vim
continuing in <SNR>3_SynSet
Executing FileType Autocommands for "*"
autocommand call s:LoadFTPlugin()

Error detected while processing BufRead Autocommands for "*.rs"..FileType Autocommands for "*"..function <SNR>10_LoadFTPlugin:
line    2:
E1126: Cannot use :let in Vim9 script
Executing FileType Autocommands for "*"

autocommand call s:on_filetype_changed(bufnr(expand('<afile>')))
```

See [rustinfo.txt](https://github.com/rust-lang/rust.vim/files/8103107/rustinfo.txt)

After some research and debugging, this fixes my error:

```diff
diff --git a/ftplugin/rust.vim b/ftplugin/rust.vim
index fb048ca..753a881 100644
--- a/ftplugin/rust.vim
+++ b/ftplugin/rust.vim
@@ -151,7 +151,7 @@ let b:undo_ftplugin = "
                 \|setlocal tabstop< shiftwidth< softtabstop< expandtab< textwidth<
                 \|endif
                 \|if exists('b:rust_original_delimitMate_excluded_regions')
-                    \|let b:delimitMate_excluded_regions = b:rust_original_delimitMate_excluded_regions
+                    \|var b:delimitMate_excluded_regions = b:rust_original_delimitMate_excluded_regions
                     \|unlet b:rust_original_delimitMate_excluded_regions
                     \|else
                         \|unlet! b:delimitMate_excluded_regions
```

But I'm not sure this is the cleanest fix :) .

**Comment by chris-morgan** [comment]
I’m confused. Your report implies that `b:undo_ftplugin` is being executed in Vim9 script mode, but that’s certainly not supposed to be the case, and would be a heavily breaking change ecosystem-wide. I can’t reproduce it, and your patch would *break* things. I think the only way forwards here is for you to identify why and how it’s working in Vim9 script mode, which could point to some wonky extension or could be a bug in Vim itself.

**Comment by acatton** [comment]
Makes sense, this would be why I'm the only one reporting this bug. I have a few plugins which I installed manually by cloning into `pack/foobar/start/`.

However, I cannot find why anything would run in vim9script:

```
$ rg -i 'vim ?9' ~/.vimrc
$ rg -i 'vim ?9' ~/.vim
$ 
```

However, I found this:

```
$ rg -i 'vim ?9' /usr/share/vim/ -g '*.vim'
/usr/share/vim/vim82/syntax/vim.vim
[…]

/usr/share/vim/vim82/autoload/dist/ft.vim
1:vim9script

/usr/share/vim/vim82/autoload/ccomplete.vim
1:vim9script noclear
6:#		Rewritten in Vim9 script by github user lacygoill
```

After some research, it lead me to this https://github.com/vim/vim/issues/9741 . So I'm sorry for the noise, it looks like an issue with vim itself :) .

Thanks again for the quick answer :+1:
