### ISSUE TITLE
Question: is there a rust.vim equivalent to vim-go's `:GoRename`

### ISSUE THREAD

**Issue by Integralist** [rust-lang/rust.vim#473]
As per the title, the `vim-go` plugin allows you to replace an identifier globally across a project by executing `:GoRename <new_name>` while the cursor is over an identifier in your code.

Is this something that exists already in the rust.vim plugin or does anyone know of any plans to support that?

Thanks!

**Comment by bodymindarts** [comment]
I have had good results with the command `ALERename` from [this plugin](https://github.com/dense-analysis/ale#2viii-refactoring-rename-actions)

**Comment by Integralist** [comment]
I have since discovered:

```
lua vim.lsp.buf.rename()
```

**Comment by chris-morgan** [comment]
It’s all a part of whatever rust-analyzer integration you may go for, which is out of scope for rust.vim. For coc, you’d want to map something to `<plug>(coc-rename)`.
