### ISSUE TITLE
Inclusion in the next Vim release

### ISSUE THREAD

**Issue by rcantangus** [rust-lang/rust.vim#57]
Could these be pushed upstream for inclusion in 7.5?  Having it available by default offers a much nicer initial experience.

**Comment by steveklabnik** [comment]
I have no idea how to do that, but I wouldn't mind.

**Comment by chris-morgan** [comment]
I believe it’s now at a stage where this would be reasonable. (I declined to do it some time back because it wasn’t stable yet, with the intention that before terribly long it would be appropriate to do it.)

**Comment by rcantangus** [comment]
Thanks.  You just email them direct to bram@moolenaar.net.

**Comment by bstrie** [comment]
@chris-morgan Did you ever manage to find time to upstream this?

**Comment by da-x** [comment]
A much older version of the plugin was upstreamed awhile back. We'll have to upstream again because of many fixes and improvements. A separate issue will be open for that.
