### ISSUE TITLE
After installing rust.vim, my colorscheme was overridden

### ISSUE THREAD

**Issue by matthiasbeyer** [rust-lang/rust.vim#65]
How to fix this?

**Comment by chris-morgan** [comment]
What do you mean by your colorscheme being overridden? If you’re speaking of this repository, you can’t mean that `'colorscheme'` was altered, because there’s nothing in here that can do that. So can you please elucidate?

**Comment by matthiasbeyer** [comment]
Seems I messed up elsewhere. Sorry for bothering you.

**Comment by matthiasbeyer** [comment]
Just for the future: The issue was neither vim nor rust.vim. The point was that I compared one vim which was running inside tmux and one which was running outside tmux. They looked different. I thought that the new plugin I installed (rust.vim) messed up my colorscheme, but as I started vim outside tmux, it just looked different. -.-'
