### ISSUE TITLE
Support for file checking beyond syntactic correctness

### ISSUE THREAD

**Issue by jonhoo** [rust-lang/rust.vim#67]
Currently, the syntastic integration (which will hopefully soon also be used by [neomake](https://github.com/benekastah/neomake/issues/275)) runs `rustc` with `-Zparse-only` to check a particular file. While this is fine, it doesn't catch the vast majority of errors that come up during development.

Obviously, just dropping `-Zparse-only` won't work, as the compiler will complain about missing imports/types, but maybe some kind of integration with `cargo` could work? Maybe look up the file tree to find `Cargo.toml`, run `cargo build`, and parse out any warning/error that pertains to the currently open file? It's not pretty, but would be extremely useful!

**Comment by Seeker14491** [comment]
Can't we use `cargo rustc -Zno-trans` like [this Atom plugin](https://github.com/AtomLinter/linter-rust) does? This will catch those errors while being faster than `cargo build`.

**Comment by da-x** [comment]
Today we have the 'cargo' Syntastic checker in `rust.vim`, plus ALE and experimental RLS. Standalone `.rs` file checking is still supported by `rust.vim` for the situation where the Rust file is really standalone. If a "errors only for the current file" filter would be useful in Syntastic, ALE, or RLS, then it can be a separate issue?

Also, for limited single-file checking, using rustfmt as a third check #80 may be an interesting option.

Anyway, this can be closed :)
