### ISSUE TITLE
strange closing braces indent 

### ISSUE THREAD

**Issue by lu-zero** [rust-lang/rust.vim#69]
currently writing

``` rust
pub struct foo {
}
```

results in:

``` rust
pub struct foo {
    }
```

**Comment by chris-morgan** [comment]
Can’t reproduce with Vim 7.4.1190.

Vim version? If it’s before 7.4.355 I’m not especially surprised; patch 355 fixed some rather egregious indenting bugs in stuff we use, we work around some of the problems before it but not all. If not, the indent settings could potentially be relevant;  I have the values `nocindent autoindent smartindent indentexpr=GetRustIndent(v:lnum)`; check the values with `:set ci? ai? si? inde?`, if the lattermost isn’t right you’re lacking a `:filetype indent on`, for the earlier ones try toggling them and see what happens.

(Also ensure that your rust.vim is up to date.)

**Comment by lu-zero** [comment]
The lattermost seems wrong even if I use `:filetype indent on`, I have Vim 7.4.1257 and I installed the updated bundled yesterday.

My setup is basically the gentoo vimrc + pathogen + rust.vim.

**Comment by lu-zero** [comment]
My exact typing is `pub struct foo {}<back><enter>`, the plugin correctly moves the `}` to the right level if it is typed as `pub struct foo {<enter>}`.

**Comment by chris-morgan** [comment]
By `<back>` are you meaning `<Left>`? Still can’t reproduce.

**Comment by lu-zero** [comment]
Yes, left. Let me try to install it on another system and compare =)

**Comment by lu-zero** [comment]
I confirm in other systems works just fine...

**Comment by da-x** [comment]
If this issue still relevant, please ping. Thanks!
