### ISSUE TITLE
rustfmt support behaves badly in conjunction with :wq when it returns an error

### ISSUE THREAD

**Issue by ketsuban** [rust-lang/rust.vim#71]
I very much like having rustfmt fix my formatting when I save, but sometimes I make syntax errors because I'm human. rustfmt proactively tries to tell me about that, and rust.vim helpfully shows me the error. However, if I've done `:wq` rather than merely `:w` Vim ends up in a strange state where the only thing open is the quickfix list with the error in it, the things I type are written into the buffer, but when I hit enter the command I typed is executed.

Possible solutions:
- Don't open the quickfix list with errors if the program is quitting.
- Interrupt the quitting if there's an error the user needs to see so they can fix their code, resave and then quit.

**Comment by da-x** [comment]
Dup of #109
