### ISSUE TITLE
Add `compiler cargo` to ftplugin/rust.vim?

### ISSUE THREAD

**Issue by ticki** [rust-lang/rust.vim#73]
So that you can do `:make` and `:cc` for populating the QuickFix list.

**Comment by joshtriplett** [comment]
This shouldn't happen unconditionally, only if searching upwards finds a Cargo.toml file.

**Comment by michael-younkin** [comment]
I think this is already implemented, you just have to run `:compiler cargo` first, then you can do `:make build`. (It's not documented for some reason.) They also have `:compiler rustc`. I assume it doesn't automatically set it up so that you're able to choose which one you want.

**Comment by joshtriplett** [comment]
@michael-younkin It'd be nice to automatically look for a Cargo.toml file, enable `:compiler cargo` if so, and enable `:compiler rustc` if not.

**Comment by somini** [comment]
It's easy to search for a "Cargo.toml" file in parent directories. 
https://github.com/rust-lang/rust.vim/pull/76#discussion_r57642575

**Comment by Victor-Savu** [comment]
I'm with @joshtriplett . At least some sane default should exist, since no action means that `GNU Make` will be used by default, which is almost never what the user wants.

**Comment by sssilver** [comment]
Please, can we have this?

**Comment by Victor-Savu** [comment]
@sssilver for what it's worth, we can at least try 😄

**Comment by da-x** [comment]
PR was merged.
