### ISSUE TITLE
vim shows whole file (with "--- More ---" scrolling) when saving

### ISSUE THREAD

**Issue by Rukenshia** [rust-lang/rust.vim#75]
So, I have some weird issues when saving files using rust.vim. Whenever I changed a file and want to save it, vim displays the whole file in that scrollable mode (--- More --- at the bottom line, scrolling with arrow keys) and only when I scroll to the bottom, the file gets saved. This does not happen without rust.vim.

I use pathogen and have nerdtree, youcompleteme, syntastic and rust.vim in my bundle folder.

`vim --version`:
```
$ vim --version
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Mar 19 2016 22:56:19)
Included patches: 1-1000
Compiled by jan@jan-laptop
Huge version with GTK2 GUI.  Features included (+) or not (-):
+acl             +farsi           +mouse_netterm   +syntax
+arabic          +file_in_path    +mouse_sgr       +tag_binary
+autocmd         +find_in_path    -mouse_sysmouse  +tag_old_static
+balloon_eval    +float           +mouse_urxvt     -tag_any_white
+browse          +folding         +mouse_xterm     -tcl
++builtin_terms  -footer          +multi_byte      +terminfo
+byte_offset     +fork()          +multi_lang      +termresponse
+cindent         +gettext         -mzscheme        +textobjects
+clientserver    -hangul_input    +netbeans_intg   +title
+clipboard       +iconv           +path_extra      +toolbar
+cmdline_compl   +insert_expand   -perl            +user_commands
+cmdline_hist    +jumplist        +persistent_undo +vertsplit
+cmdline_info    +keymap          +postscript      +virtualedit
+comments        +langmap         +printer         +visual
+conceal         +libcall         +profile         +visualextra
+cryptv          +linebreak       +python          +viminfo
+cscope          +lispindent      -python3         +vreplace
+cursorbind      +listcmds        +quickfix        +wildignore
+cursorshape     +localmap        +reltime         +wildmenu
+dialog_con_gui  -lua             +rightleft       +windows
+diff            +menu            -ruby            +writebackup
+digraphs        +mksession       +scrollbind      +X11
+dnd             +modify_fname    +signs           -xfontset
-ebcdic          +mouse           +smartindent     +xim
+emacs_tags      +mouseshape      -sniff           +xsmp_interact
+eval            +mouse_dec       +startuptime     +xterm_clipboard
+ex_extra        -mouse_gpm       +statusline      -xterm_save
+extra_search    -mouse_jsbterm   -sun_workshop    +xpm
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "$VIM/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/usr/local/share/vim"
 f-b for $VIMRUNTIME: "/usr/share/vim/vim74"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_GTK  -pthread -I/usr/include/gtk-2.0 -I/usr/lib/gtk-2.0/include -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/libdrm -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng16 -I/usr/include/pango-1.0 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/harfbuzz -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/harfbuzz -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include   -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1       
Linking: gcc   -L/usr/local/lib -Wl,--as-needed -o vim   -lgtk-x11-2.0 -lgdk-x11-2.0 -lpangocairo-1.0 -latk-1.0 -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lpangoft2-1.0 -lpango-1.0 -lgobject-2.0 -lglib-2.0 -lfontconfig -lfreetype -lXt -lX11 -lSM -lICE  -lm -lncurses -lacl -L/usr/lib/python2.7/config -lpython2.7 -ldl -lutil -lm -Xlinker -export-dynamic 
```

**Comment by chris-morgan** [comment]
That sounds extremely odd and I can’t imagine what’s going on at all. How are you triggering the save? Something other than `:w`, I presume?

**Comment by Rukenshia** [comment]
tried all the options, `:w`, `:wq`, `:w!`, `:wq!` followed by the return key. This only happens for *.rs files, so it has to be rust.vim or any of the associated packages. I dont know how to track that down, though.

I forgot to mention earlier that I did compile vim myself (in order to get python2.7 support for youcompleteme), I also tried various tags (latest was `v7.4.1615`, currently I tried to use `v7.4.1000`).

**Comment by chris-morgan** [comment]
OK, an auto-command is all I can think of that could possibly be involved. Try `:au BufWrite,BufWritePre,BufWritePost,BufWriteCmd` and see if there’s anything relevant. `*` or `*.rs` are the most probable [file name] patterns to note.

For myself on Rust files in general, syntastic’s `call s:BufWritePostHook()` is the only one.

Next step in diagnosing if this doesn’t point something out will be going through the options that are set (`:set`) and resetting them (`:set optionname&vim`, option by option) until the problematic behaviour goes away.

**Comment by Rukenshia** [comment]
Okay, I found what is causing the problem: the `rustfmt_autosave` option. Is that expected behavior for the option?

**Comment by leeola** [comment]
Experiencing the same here, using `NVIM 0.1.1 (compiled Feb  2 2016 15:27:08)`. If i disable the `rustfmt_autosave` option, the problem goes away

**Comment by leeola** [comment]
In my case, it seems to be invalid syntax causing rustfmt to panic, and then rust-lang does what is described in this issue. When i use specific code, rustfmt panics, and rust.vim shows the described behavior. When i comment out that code, rust.vim does not panic and rust.vim does not show the described issue.

The error i receive when running appears to be the same as seen here: https://github.com/rust-lang-nursery/rustfmt/issues/835

**Comment by oblitum** [comment]
Same here :-/

**Comment by leeola** [comment]
As a sidenote, i also noticed that if you don't have `rustfmt` in your PATH properly, rust.vim will also print the `--- more ---` scroll thing. So make sure your paths are correct as well :)

**Comment by oblitum** [comment]
@leeola really thanks for your comment, I had just upgraded my Rust setup and forget to update the PATH regarding cargo installs =)

auto fmt is working normally now with `rustfmt` on PATH.

**Comment by oblitum** [comment]
Ah, but still, if there's an error in the file when formatting, that issue still happens.

**Comment by russmack** [comment]
It still does this -- More -- thing if there's an error in the source.

**Comment by oblitum** [comment]
> It still does this -- More -- thing if there's an error in the source.

Correct. And, IIRC, it has been fixed before and then it's happening again...

**Comment by russmack** [comment]
Ah.  This may be something to do with a conflict between cargo-fmt and rustfmt and a change in their packaging.  Try:
`cargo uninstall rustfmt`
`cargo install rustfmt`
And ensure ~/.cargo/bin is in your $PATH.
Ref: https://www.reddit.com/r/rust/comments/3x1ket/rustfmt_is_now_supereasy_to_try_out/

**Comment by oblitum** [comment]
After recompiling I now get a bunch of "rustfmt returned error" error messages in Vim...

**Comment by bradleybeddoes** [comment]
@oblitum I believe I am seeing the same issue.

If I make a deliberate syntax error and save a file I end up with the following messages. Syntax issues are correctly highlighted / navigable.

```
rustfmt returned error
Error detected while processing BufWrite Auto commands for "*":
E21: Cannot make changes, 'modifiable' is off
Error detected while processing BufWrite Auto commands for "<buffer=1>":
E21: Cannot make changes, 'modifiable' is off
```

On save of a file that is syntactically correct, `rustfmt` runs, formats the file as you'd expect and write occurs without error.

Updated plugins as of 10 minutes prior to this comment.

**Comment by oblitum** [comment]
This should be reopened as it's still an issue. Simple steps to reproduce:

- `let g:rustfmt_autosave = 1`
- `:w` a rust file with contents:
```rust
fn main() {
    let foo: Vec<_> = vec![1, 2, 3];
    x
    foo.push(4);
}
```
`x` will force an error that will make file contents to be dumped in the command line.

**Comment by oblitum** [comment]
I've opened a new issue for tracking this problem in specific.

**Comment by venantius** [comment]
I have also run into this issue. In general rust.vim doesn't handle invalid syntax here properly - I'd guess that if Syntastic can tell that the syntax is invalid then we shouldn't even attempt to invoke rustfmt, or maybe the better approach is for rustfmt to do a best effort and then return, but in either case I've had to just make failures silent and keep going, which is frustrating.

**Comment by mark-i-m** [comment]
I don't know if people are still having this problem... I was...

I fixed it by simply git pulling rust.vim again. I am using pathogen, which does not automatically update pluggins. Consequently, my version of rust.vim was out of date and not accepting new syntax. Thus, it was triggering the errors above, even though my code was compiling.

**Comment by mark-i-m** [comment]
I possibly need to update my rustfmt also...

**Comment by oblitum** [comment]
@mark-i-m as commented at https://github.com/rust-lang/rust.vim/issues/109#issuecomment-251402654, `let g:rustfmt_fail_silently = 1` completely avoids the issue in any case, it's what I've been using since I came to known of it.

**Comment by mark-i-m** [comment]
Hmm... That's good to know!

Thanks :)
