### ISSUE TITLE
Contextual keyword `default`

### ISSUE THREAD

**Issue by bluss** [rust-lang/rust.vim#79]
Rust's got a new contextual keyword, only an unstable feature so far, `default` that is used by specialization.

**Comment by chris-morgan** [comment]
So, it can come before `impl` (i.e. `default impl`), or before any trait item (whatever they’re called), e.g. `default fn`, `default type`, probably `default const` with associated types? (I haven’t stopped to consider the implications *at all*, dunno if it’d be stupid.)

Yeah, that’s straightforward.

**Comment by bluss** [comment]
Nice, thank you!
