### ISSUE TITLE
incorrect completion

### ISSUE THREAD

**Issue by kindlychung** [rust-lang/rust.vim#81]
If you type `std::pro` and then tab, the first suggestion that comes up is `Process`, which is wrong according to racer:

```bash
racer complete std::pro
MATCH process,1,0,/Users/kaiyin/rust_source/rust/src/libstd/process.rs,Module,/Users/kaiyin/rust_source/rust/src/libstd/process.rs
```

**Comment by chris-morgan** [comment]
Racer support is in the [vim-racer](https://github.com/racer-rust/vim-racer) repository, not here.
