### ISSUE TITLE
Doc-Comment don't highlight properly

### ISSUE THREAD

**Issue by giodamelio** [rust-lang/rust.vim#82]
[`///` and `//!` comments](https://doc.rust-lang.org/book/testing.html#documentation-tests) don't show up as comments.

**Comment by steveklabnik** [comment]
Hmmm, they show up as different than // comments, but are still highlighted, for me. What are you seeing?

**Comment by chris-morgan** [comment]
The types they highlight as are linked by default to SpecialComment. Most colour schemes handle this properly; yours may not. But it’s a colour scheme issue, not a rust.vim issue.

**Comment by giodamelio** [comment]
Ah, thanks.
