### ISSUE TITLE
Explain how to install rustfmt

### ISSUE THREAD

**Issue by mbyio** [rust-lang/rust.vim#89]
As a new Rust user, I was very confused about why Rustfmt wasn't working. I enabled it to run automatically on save, but if you don't have Rustfmt installed then it just echo's the source file to the terminal - no error messages or anything. So it would be really helpful if you could either add an error message or a note in the docs telling people to install rustfmt using `cargo install rustfmt`. Thanks!

**Comment by grangoku** [comment]
@michael-younkin thanks for this. I was confused as a new user as well. I use vim-plug so I just changed my rust import to `Plug 'rust-lang/rust.vim', { 'for': [ 'rust' ], 'do': 'cargo install rustfmt' }
`

**Comment by rofrol** [comment]
I think it should be rather

```
Plug 'rust-lang/rust.vim', { 'for': [ 'rust' ], 'do': 'rustup component add rustfmt' }
let g:rustfmt_autosave = 1
let g:rustfmt_options = '--edition 2018'
```

We need to `--edition`, otherwise rustfmt will use 2015 edition.

https://github.com/rust-lang/rust.vim/issues/368#issuecomment-552132755

**Comment by da-x** [comment]
Mentioned rustfmt installation in README.md. Plugin currently defaults to `'--edition 2018'` in absence of `rustfmt.toml`.
