### ISSUE TITLE
syntastic is broken (unresolved imports)

### ISSUE THREAD

**Issue by wagnerf42** [rust-lang/rust.vim#92]
hi,
syntastic gives me wrong error messages.
the code compiles fine with cargo though.

I have my own crate with submodules.
when in submodule1 I import some class from submodule2 with "use submodule2::MyClass";
syntastic launches rustc -Zno-trans src/submodule1.rs which results in unresolved imports (E0259).
I asked on irc about that and they told me I should compile the whole crate using cargo and not just the single file.

**Comment by jgouly** [comment]
Anyone know if there is a way to fix this?

**Comment by eremzeit** [comment]
I was looking into this too.  I imagine the fix would involve passing arguments via the `let g:syntastic_rust_args = "--my --args --here"` directive that would cause the whole crate to be considered when compiling.  If I figure out that it is indeed possible I'll share my findings here.

**Comment by eremzeit** [comment]
I'm using the nightly version of rustc (`rustc 1.15.0-nightly`) and reverting the following commit fixed the issue for me: https://github.com/rust-lang/rust.vim/commit/c3dcd5f5c52df792b3acfd2bcc1cded7627fb961

**Comment by abbec** [comment]
I also get this issue, it is really annoying. Is there something that can be done to work around it?

**Comment by mitchmindtree** [comment]
I just pulled the latest `rust.vim` changes for the first time in what must be nearly a year and I'm now running into this also. @eremzeit's fix of reverting [`c3dcd5f`](https://github.com/rust-lang/rust.vim/commit/c3dcd5f5c52df792b3acfd2bcc1cded7627fb961) worked for me, but seems a little hackish and means we miss out on proper inter-module related errors.

**Comment by wagnerf42** [comment]
I somehow managed to get syntax checking using cargo clippy
https://github.com/wagnerf42/vim-clippy

it's a bit slow but i'm happy with it.

**Comment by timlyo** [comment]
I'm still running into this problem, was there ever a fix?

**Comment by wagnerf42** [comment]
as far as I know there is no fix for it. you can try my vim-clippy plugin (see previous comment) if you don't mind some waiting times.

**Comment by timlyo** [comment]
Thanks. I think I'll just stick with compiler output for now though.

**Comment by agaviria** [comment]
The syntastic errors are a bit annoying and a real shame for those who use vim as their text editor of choice. @wagnerf42 I just tried to go with your alternate solution but `cargo install clippy` fails with 51 build errors.

**Comment by wagnerf42** [comment]
that's because you need to be in nightly in order to install clippy.

**Comment by agaviria** [comment]
Yep, I was already on nightly but just an older branch.  Did an update and it worked flawlessly.  Thanks.

**Comment by githubxxcc** [comment]
Have you tried with this? Having 'rustc' alone as the checker gives me the unresolved import issue. 
`let g:syntastic_rust_checkers = ['cargo', 'rustc']`

**Comment by da-x** [comment]
`cargo` is now the default checker if nothing is specified, and it's valid for the very large majority of cases where a `rustc` breaks due to dependencies. Please re-open if relevant.

Thanks!
